### ISSUE TITLE
Investigate and document Workbox

### ISSUE THREAD

**Issue by postphotos** [xwp/pwa-wp#1]
_As a developer in the WordPress ecosystem, I should have a better way to share assets in complex usage of progressive web apps._

- [ ] AC1: Record level of effort to set up a working Workbox project, sharing any quirks and oddities and lessons learned along the way.

https://developers.google.com/web/tools/workbox/

**Comment by kienstra** [comment]
**Question About Closing This Issue**

Hi @postphotos,
Do you think we could close this issue? 

Several of us discussed and researched Workbox in #5 (Propose a Workbox solution for WordPress). Though I should have added findings to this issue, I think the discussion in #5 might be enough.
