### ISSUE TITLE
Plugin updater notification engine for PWAs

### ISSUE THREAD

**Issue by postphotos** [xwp/pwa-wp#10]
As a developer, I should have an approach to leverage PWA notifications in my app. 

 - [ ] AC1: Research and define approach for support of PWA notifications based on the findings from #1.
 - [ ] AC2: Prototype an example of what notifications could look like based on the shared approach from #7.

**Comment by kevincoleman** [comment]
Thanks for the acceptance criteria here, @postphotos. Do we think this may need an AC of: define related API endpoints/functionalities for updater notification engine?

**Comment by kienstra** [comment]
**Question About Updater**

Hi @postphotos,
Does 'updater' refer to plugin update notices like:

<img width="1252" alt="new-version-available" src="https://user-images.githubusercontent.com/4063887/41921614-e2ca7bb4-7928-11e8-9464-2571a6728796.png">

Also, does this issue involve a general API for any plugin to create notices, not only for plugin updates?

Thanks, Leo!

**Comment by westonruter** [comment]
I'm not sure what “plugin updater” is referring to. Notifications for plugin updates is not related to PWA. I think in general this is just about looking at ways to facilitate plugin developers to be able to show notifications to the user. We shouldn't focus on this yet, however. We can look at notifications once we have the base service worker API in place and we start looking at abstracting it with Workbox, for example.

**Comment by postphotos** [comment]
Closing for now until further interface questions are discuscsed.

**Comment by amedina** [comment]
Agree on postponing this discussion to later. One comment now is that when we talk about "push notifications" we refer to a notifications service that interacts with the SW API to provide notifications to end users (i.e. want to receive scores updates?). Here is some docs about it: https://developers.google.com/web/fundamentals/push-notifications/
Let's discuss more soon.

**Comment by nico-martin** [comment]
Same here. I don't think WordPress should provide a "push notifications" feature. It needs the ServiceWorker API so any developer could use that to create their own "push notification center" with the messaging service she/he prefers.
