### ISSUE TITLE
Suboptimal rewrite handling causes plugin conflicts

### ISSUE THREAD

**Issue by swissspidy** [xwp/pwa-wp#1075]
I ran into constant rewrite issues with Polylang and the PWA plugin [as reported here](https://wordpress.org/support/topic/conflicting-rewrite-rules-breaking-single-posts/), so I had to disable the latter for now.

Turns out the way the PWA plugin adds and potentially flushes rewrite rules on `init` is flawed. [See Chouby's explanation](https://wordpress.org/support/topic/conflicting-rewrite-rules-breaking-single-posts/#post-17206369).

**Comment by westonruter** [comment]
Actually, the flushing is happening at `admin_init`. And is adding rewrite rules at `init` too early?

**Comment by swissspidy** [comment]
As per the support topic, Polylang deletes the `rewrite_rules` option so that WP generates it upon next page load.

The PWA code in question here:

https://github.com/GoogleChromeLabs/pwa-wp/blob/62961cdddd24c3aa5d49fc39a219a92d085f8f59/wp-includes/class-wp.php#L9-L31

The PWA plugin calls `$wp_rewrite->wp_rewrite_rules()` on `init`. If the option does not exist, it flushes the rewrite rules. If in the admin, this will cause 2 flushes because of the flush hooked into `admin_init`. That's why the quick fix would be to just call `get_option( 'rewrite_rules')` instead of `$wp_rewrite->wp_rewrite_rules()`. So just a 1 line change.

However, flushing like that should typically only occur on plugin activation/deactivation or when a new site is created in Multisite, or (if the plugin has that) in some sort of upgrade routine / migration script. That's how we do it in the Web Stories plugin for example: https://github.com/GoogleForCreators/web-stories-wp/blob/afe6e41af3f0086181a4cdf12060c2c2b6d4bf29/includes/Infrastructure/ServiceBasedPlugin.php#L116-L208

**Comment by westonruter** [comment]
Alternatively, we can avoid flushing the rules entirely because the plugin also contains this failsafe code which runs at the `parse_query` action:

https://github.com/GoogleChromeLabs/pwa-wp/blob/62961cdddd24c3aa5d49fc39a219a92d085f8f59/wp-includes/service-workers.php#L215-L218

**Comment by lkraav** [comment]
So is there a code change planned?

**Comment by westonruter** [comment]
Yes. I need to set aside some time this month to do this and the 0.8 release.

**Comment by westonruter** [comment]
Here we go: #1096
