### ISSUE TITLE
Standardize a WP approach to app manifest

### ISSUE THREAD

**Issue by postphotos** [xwp/pwa-wp#11]
As a developer of a PWA, I should use an app manifest to describe what my application does - knowing that there can only be one. I should be respectful of other app approaches, and I should have some way to play nicely if there are several app manifests.

AC1: Based on discovery of WP approaches (core, plugins, themes) from #1, document how app manifests are used.
AC2: Provide a basic hierarchy (or some core definition) on a perhaps per-theme basis to establish direction.

Scenario:
A user installs _Super Awesome Plugin_ and _Cool PWA theme_. They both use PWA features; whose app manifest rules them both? We _shouldn't_ go overkill (i.e. [theme template overrides](https://developer.wordpress.org/themes/basics/template-hierarchy/), which works well but is quite complex) but we should find a straightforward approach here.

**Comment by kienstra** [comment]
**Search Results For manifest.json**

[Here are the plugins](https://wordpress.org/plugins/search/manifest.json/) on WordPress.org that appear in a search for `manifest.json`.

**Comment by kienstra** [comment]
This might be a good issue to work on this week (June 19th). It's fairly self-contained.

**Comment by westonruter** [comment]
This can largely lift the Jetpack implementation: https://github.com/Automattic/jetpack/blob/master/modules/pwa/class.jetpack-pwa-manifest.php
