### ISSUE TITLE
WP activation error

### ISSUE THREAD

**Issue by rollingryan** [xwp/pwa-wp#111]
When activating the plugin I'm getting an ErrorException:
```
ErrorException (E_USER_NOTICE)
has_cap was called with an argument that is deprecated since version 2.0.0! Usage of user levels is deprecated. Use capabilities instead.
```

I tracked the problem down to the `wp_pwa_admin_actions()` method where I found replacing the third parameter of `add_menu_page` needs to be changed from `1` to `'Administrator'`:

```
	function wp_pwa_admin_actions() {
		$icon_url	= trailingslashit(plugin_dir_url( __FILE__ )) . "assets/wp_pwa_20x20.png";
		$position	= 64.999989; //Right before the "Plugins"

		add_menu_page(
			'PWA - Admin',
			'PWA',
			'Administrator', // was 1
			'wp-pwa-admin',
			array($this, 'render_wp_pwa_admin'),
			$icon_url,
			$position
		);
	}
```

**Comment by westonruter** [comment]
Hi there. You're reporting an issue for the wrong plugin. Please see https://github.com/wp-pwa/wp-pwa-or https://github.com/frontity/wp-plugin
