### ISSUE TITLE
Create better installation/use path

### ISSUE THREAD

**Issue by kevincoleman** [xwp/pwa-wp#113]
This plugin does a great job at enabling developers to achieve PWA functionalities, but it doesn’t explain itself. This is primarily a documentation issue.

Looking at the docs, it’s easy to learn about PWAs—but it’s not clear what you get out of the box with this plugin, and what your next follow-up steps are.

Suggested: Add a top-level section to the plugin description that tells you what you get for free and what you need to do to reach “full PWA” status.

Some example questions people may have:
What else needs to be done after installation to have a properly-registered service worker? If nothing, where should devs access the already-installed one?
Where should a dev/user go to make changes to their manifest.json? Should those changes be made directly to a source file, or by editing WordPress values, or both?

Closing the educational gap for people will make this plugin much more usable.

I suspect @postphotos will agree heartily.

**Comment by lkraav** [comment]
Exactly this discussion https://twitter.com/lkraav/status/1055903357880147968

I've had 0 time to dig into it myself thus far. Sure would be nice to get a PR from somewhere..

**Comment by kevincoleman** [comment]
Fantastic that others are thinking of this. :)

@westonruter is there anyone in particular that could explain the ideal usage path? I’d be happy to spend some time documenting it in a n00b-ready fashion.

**Comment by lkraav** [comment]
https://github.com/wprig/wprig/pull/212 is the only downstream implementation in the wild I know of, other than @westonruter's own stuff.

**Comment by westonruter** [comment]
You guys are right. The problem is that the foundation of the plugin is not solidified. So the examples that have been built so far have been done to give a feel for what is possible, but the API itself is not locked in yet.

In January as we finally get the feature project for core kicked off, we'll at that point get more eyes on the API. We'll also at that time get a better idea for what should be in scope of the feature plugin, and what should be left for other plugins and themes to implement on their own.

The other thing is that there is no one PWA that all developers should be targeting. It's intended that developers would pick and chose which PWA features are right for their use case. Does every site need push notifications? Please no. Does every site need to implement app shell (single-page app + smooth page transitions)? No.

As part of the feature project, we should make it clear which features make sense for the 80% of sites, and then leave the other 20% with good APIs that make it straightforward to implement what they want.

**Comment by kevincoleman** [comment]
Ah, I see. So, if it’s a case of not really having the API settled, it’s tempting to wait to start providing instructions for implementers.

Would it be ridiculous to suggest that we should draft a working copy that can iterate? I totally agree that not every site should implement all PWA features, but I’m not sure I’m sold that we shouldn’t start defining the jump-off points as they are right now. So, rather than defining what every site should have as part of its PWA offerings, what about viewing it as a get-started guide—a guide that points devs in the right direction for each feature and then helps them implement from there. I would foresee such a guide being structured like this:

**If I want to add a manifest.json, what are the steps to do so?**
1. Check to be sure you’re not already registering a manifest file that will get overridden
2. Create a starter manifest.json file
3. Update or create the WordPress hook (at such and such location)
4. Review manifest docs to continue developing the manifest file

**If I want to implement notifications on my site, what are the first steps to get there?**
1. Create a standard service worker
2. Register the service worker in your theme header
3. Add notification implementations

**If I want to make my site into a single-page application (App Shell), what are the steps to make it work?**
1. ...
2. ...
...

You’ll have to forgive my lack of knowledge on the implementations of all these things—I’m still picking them up as it pertains to the WordPress ecosystem. Sounds like that ecosystem is still what’s in rapid development.

Even if these steps outline what a dev _should_ need to do, and points out places where the API is still unsettled, that might help make this plugin of some use. After the API does settle, it would be a great scaffold for documentation, a “get started” guide, or even just the Admin UI that may need to be developed.

**Comment by amedina** [comment]
The feature plugin seeks mainly to enable the foundational building blocks on top of which general PWA features can be built. As @westonruter pointed out, we will be kicking off the integration to core effort in Q1 next year and the full definition of the API entry points will be settled. We need to capture the fact that the features enabled by the plugin are low-level API primitives such as specifying caching and serving strategies; all general PWA features such as offline access to recently visited articles, the APP shell model, and the rest, are separate.

**Comment by kevincoleman** [comment]
I don’t mean to sound like what you’re doing doesn’t help devs—I just think it may be helpful if they understand that the goal of this plugin is to better expose WordPress to be able to support a “blessed” path to PWAs, and that it doesn’t yet propose to be an out-of-the box solution for actually converting sites to PWAs (yet).

Is the idea that other plugin devs would provide the plugins that do the actual site conversion steps, using this plugin (or core features after merge) as a dependency?

**Comment by westonruter** [comment]
@kevincoleman Yes, and you're right. I see actually that the readme does not make the purpose of the plugin clear. It's not intended to be the complete PWA solution, but rather to provide the building blocks for themes and plugins to implement PWA features.

So the key work in core feature proposal will be identifying where the line is drawn between a building block and a core feature. For example, precaching block editor screen and its assets would be a clear example as something which should be in core. Another example of what should make sense for core is the offline/500 error pages. But then going beyond this and providing offline access to arbitrary pages of a site—this would be theme/plugin scope.

What will be needed as well is a series of recipes for how to use the PWA ingredients in this plugin to make delicious websites. A few examples on hand now:

* Adding offline/500 error templates to a theme:
  * https://github.com/westonruter/twentyseventeen-westonson/blob/master/offline.php
  * https://github.com/westonruter/twentyseventeen-westonson/blob/master/500.php
  * https://github.com/westonruter/twentyseventeen-westonson/blob/a546f0cb1e6e2715cd8a251a1fcc6780d7c7f22f/functions.php#L199-L250
  * See also WP Rig: https://github.com/wprig/wprig/pull/212.
* Opt-in to using stale-while-revalidate for navigation request: https://gist.github.com/westonruter/f848013108672568be6dcde153f9ca37
* Implementing streaming responses: https://github.com/westonruter/twentyseventeen-westonson/pull/2
* Implementing app shell (SPA with smooth page transitions via AMP): https://github.com/ampproject/amp-wp/pull/1519

All of these examples are subject to change as the API evolves.

For a list of features which you could look at for creating a “blessed” PWA, you could refer to this 
Progressive Web App Checklist: https://developers.google.com/web/progressive-web-apps/checklist

For the “Page transitions don't feel like they block on the network” point, this could be satisfied in a few ways:

* **Streaming responses**, but personally I'm not entirely sold on the value of this approach for WordPress.
* **App shell**, works well if site can be served fully as AMP, but can still be overkill if not strictly required (e.g. essential if persistent audio player is needed during navigation)
* **Prefetching links**, e.g. [Quicklink](https://github.com/GoogleChromeLabs/quicklink) which is a very low lift and doesn't even require service worker

Going the step further to satisfy “All app URLs load while offline” then this would require the service worker to be caching the site's URLs as well to then serve either with network-first or stale-while-revalidate strategies.

**Comment by westonruter** [comment]
> I suppose it might serve the community well to disclose that in the plugin’s description

See #114.
