### ISSUE TITLE
Lighthouse says "Manifest start URL is not valid"

### ISSUE THREAD

**Issue by betayazilim** [xwp/pwa-wp#1137]
Hi there,
I couldn't find a document where to start with this plugin.
There are many documents around, most of them are way too technical but there is none to lead how to start.

1. I installed and activated plugin
2. Set shortname - General Settings
3. Offline browsing checked - Reading Settings

Then tested if it works via chrome browser.
Right click - Inspect- Lighthouse-Analyze page load

I got error message like below.
Could you please give simple, step by step installation guide.

https://i.imgur.com/dk6UkOc.png

PWA - INSTALLABLE
Web app manifest or service worker do not meet the installability requirements 1 reason

Failure reason -- Manifest start URL is not valid

I also have error for "Manifest doesn't have a maskable icon"  but find documentation about it.

**Comment by westonruter** [comment]
> Failure reason -- Manifest start URL is not valid

What's the URL of your site? I need to know what the `start_url` is set as.

> I also have error for "Manifest doesn't have a maskable icon" but find documentation about it.

Good question. This is set in the Customizer (`/wp-admin/customize.php`), specifically in the Site Identity panel. There is #915 for eliminating the reliance on the Customizer.

**Comment by westonruter** [comment]
I see you cross-posted your question on the support forum: https://wordpress.org/support/topic/how-to-use-it-72/

Closing that topic as a duplicate.

**Comment by betayazilim** [comment]
> > Failure reason -- Manifest start URL is not valid
> 
> What's the URL of your site? I need to know what the `start_url` is set as.
> 
> > I also have error for "Manifest doesn't have a maskable icon" but find documentation about it.
> 
> Good question. This is set in the Customizer (`/wp-admin/customize.php`), specifically in the Site Identity panel. There is #915 for eliminating the reliance on the Customizer.

Hi Weston,
Thanks for reply. [Here](https://www.laptop.com.tr/) is my website. 
I am trying to understand how I should make it right.

**Comment by betayazilim** [comment]
I have added start url in to a file called site.webmanifest.
It it right approach?

**Comment by westonruter** [comment]
@ned-bs You don't actually need to add a web manifest yourself. The plugin does this automatically. You can see it doing so as follows:

```html
<link rel="manifest" href="https://www.laptop.com.tr/wp-json/wp/v2/web-app-manifest">
```

That manifest has the `start_url` set to https://www.laptop.com.tr/ which seems correct.
