### ISSUE TITLE
Add ability to customize the theme color without relying on custom background

### ISSUE THREAD

**Issue by aristath** [xwp/pwa-wp#116]
In my use-case the client would like their header-color to be used as theme-color, so a filter would be nice here.

**Comment by DoronYosha** [comment]
Hi @aristath 
Did you managed to customize the theme color?
Im looking how to do it :-)

**Comment by westonruter** [comment]
@DoronYosha currently you can do so via the `web_app_manifest` filter: https://github.com/GoogleChromeLabs/pwa-wp/wiki/Web-App-Manifest#filtering
