### ISSUE TITLE
Unable to register callback on `wp_front_service_worker` action

### ISSUE THREAD

**Issue by su-narthur** [xwp/pwa-wp#119]
I'm trying to register a service worker in a plugin I'm developing. I've installed `pwa-wp`, and then added this to my [plugin-name].php file, and it isn't doing anything.

```php
function registerServiceWorker()
{
	var_dump('hello');die;
}

\add_action(
	"wp_front_service_worker",
	"registerServiceWorker"
);
```

What do I need to do to be able to use this action so I can go on to register my service worker script?

Thanks!

**Comment by westonruter** [comment]
The action only is triggered when the service worker is actually being served. So you'll not see `registerServiceWorker()` invoked on regular requests. Only the request to the endpoint that serves back the service worker JS will result in it getting called.

**Comment by su-narthur** [comment]
Thanks! In general, what are the steps I need to work through to get a service worker running?

**Comment by westonruter** [comment]
@su-narthur you can use examples [from the readme](https://github.com/xwp/pwa-wp#service-workers), but otherwise it depends on heavily what you want to use the service worker for. You'd be better off referring to Workbox for general use cases: https://developers.google.com/web/tools/workbox/guides/common-recipes

**Comment by westonruter** [comment]
The service worker installation script should be printed at the `wp_print_scripts` action as can be seen here: 

https://github.com/xwp/pwa-wp/blob/c3b06fe6f7cfc78538c2b256448a41e4a050602d/wp-includes/default-filters.php#L10-L13

The logic for `wp_print_service_workers()` is as follows:

https://github.com/xwp/pwa-wp/blob/733563f46996ea2d5aaf52a576971f92c3748164/wp-includes/service-workers.php#L112-L191

It could be that the `$on_front_domain` variable is `false` if you are on `localhost` the `home_url()` is not the same. That's where you can try debugging.

**Comment by su-narthur** [comment]
@westonruter Yeah, that seems like it may be the problem.  `$_SERVER['HTTP_HOST']` evaluates to `localhost:8000`, whereas `wp_parse_url( home_url(), PHP_URL_HOST )` evaluates to just `localhost` without the port, so `$on_front_domain` ends up as `false`. This doesn't appear to be an issue with my settings, becuase I have both the WordPress Address and the Site Address settings set to `http://localhost:8000`.

Would you be interested in a PR that accounted for ports on localhost?

**Comment by westonruter** [comment]
@su-narthur yes, a PR would be great!

**Comment by su-narthur** [comment]
@westonruter Great!

I'm trying to run the phpunit tests, but I'm getting this error:

> Cannot open file "/Users/work/ProgrammingProjects/wp-avorg-dev/pwa/node_modules/wp-dev-lib/phpunit-plugin-bootstrap.php".

When I look inside `node_modules/wp-dev-lib`, there isn't any file named `phpunit-plugin-bootstrap.php` (or any php files at all at that level).

Have I missed a step?

**Comment by narthur** [comment]
Changed the path in phpunit.xml to "node_modules/wp-dev-lib/sample-config/phpunit-plugin-bootstrap.php". Now the error is:

> Fatal error: Unable to locate wordpress-tests-lib in ...

**Comment by westonruter** [comment]
@su-narthur I realize the first issue is due to the plugin not being updated to account for changes in dev-lib 1.0.0. I've opened a PR to fix that: https://github.com/xwp/pwa-wp/pull/121

Please try basing your changes off of that branch.

And for PHPUnit, yes, the plugin bootstrap is expecting to be running in an environment where wordpress-develop is available, as can be seen here: https://github.com/xwp/pwa-wp/blob/master/contributing.md#phpunit-testing

For the sake of expediency you can bypass the `pre-commit` hook by doing `git commit --no-verify`. Or you can skip PHPUnit specifically via `DEV_LIB_SKIP=phpunit git commit`.

**Comment by narthur** [comment]
I've created a PR for this change. It indeed fixes the issue where no service worker was getting registered at all. However, my code still fails to register my own service worker or add wp-content image caching. (The only images that are cached are wp-admin images, which seem to be cached by default.)

**Comment by westonruter** [comment]
> However, my code still fails to register my own service worker or add wp-content image caching. (The only images that are cached are wp-admin images, which seem to be cached by default.)

Please share the full code you are using. Ideally this would be in Gist form that has a fully functioning plugin we can drop in.

**Comment by narthur** [comment]
@westonruter You probably caught this, but just in case: The link in my last comment is to a specific branch. It's the branch that the service worker stuff is on. So you'll need to be sure to download the zip of that branch.

**Comment by westonruter** [comment]
@su-narthur when I look at the service worker upon activating your plugin, I see it contains just:

> hello world

When I remove `var_dump('hello world');die;` from `\Avorg\Pwa::registerServiceWorker()` then I get:

> Fatal error: Uncaught Error: Class 'Avorg\WP_Service_Worker_Caching_Routes' not found in /app/public/content/plugins/wp-avorg-plugin-topic-detail-page/class/Pwa.php on line 36
>
> Error: Class 'Avorg\WP_Service_Worker_Caching_Routes' not found in /app/public/content/plugins/wp-avorg-plugin-topic-detail-page/class/Pwa.php on line 36


You need to add a backslash:

```diff
-				'strategy'  => WP_Service_Worker_Caching_Routes::STRATEGY_CACHE_FIRST,
+				'strategy'  => \WP_Service_Worker_Caching_Routes::STRATEGY_CACHE_FIRST,
```

When I fix that then I get another error:

> Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'registerServiceWorker' not found or invalid function name in /app/public/core-dev/src/wp-includes/class-wp-hook.php on line 286

So yeah, it seems you need to debug your code a bit more.

**Comment by narthur** [comment]
@westonruter Where do I go to see these error messages?

**Comment by westonruter** [comment]
Just load the service worker directly in the browser by going to `/?wp_service_worker=1`. Make sure `WP_DEBUG` is enabled. You can also see errors in your system's PHP error log.

**Comment by westonruter** [comment]
Please share the context for where you are calling `wp_register_service_worker_caching_route()`.

Actually, you can refer to this example:

https://github.com/ampproject/amp-wp/blob/9c35c3d15ff07dbd00ca2dc894962a9595245cdf/includes/class-amp-service-workers.php#L39

https://github.com/ampproject/amp-wp/blob/9c35c3d15ff07dbd00ca2dc894962a9595245cdf/includes/class-amp-service-workers.php#L79-L108

**Comment by su-narthur** [comment]
@westonruter I got a little closer to tracking this down. I noticed that only the backend service worker is being registered, not the front-end one, even though it's being generated fine when I hit the endpoint. I added a catch to the code that generates the script to register the service workers, and got this error message back:

> DOMException "SecurityError" "Failed to register a ServiceWorker: The origin of the provided scriptURL ('https://localhost:8000') does not match the current origin ('http://localhost:8000')."

This is the registration script that got generated:

```
<script>
  if (navigator.serviceWorker) {
    window.addEventListener('load', function() {
      {
        let updatedSw;
        navigator.serviceWorker.register(
          "https:\/\/localhost:8000\/?wp_service_worker=1", {
            "scope": "\/"
          }).then(reg => {
          document.cookie = 'wordpress_sw_installed=1; path=/; expires=Fri, 31 Dec 9999 23:59:59 GMT; secure; samesite=strict';
        }).catch(function(error) {
          console.log(
            error,
            error.name,
            error.message
          );
        });
      } {
        let updatedSw;
        navigator.serviceWorker.register(
          "http:\/\/localhost:8000\/wp-admin\/admin-ajax.php?action=wp_service_worker", {
            "scope": "\/wp-admin\/"
          }).then(reg => {
          document.cookie = 'wordpress_sw_installed=1; path=/; expires=Fri, 31 Dec 9999 23:59:59 GMT; secure; samesite=strict';
        }).catch(function(error) {
          console.log(
            error,
            error.name,
            error.message
          );
        });
      }
      let refreshedPage = false;
      navigator.serviceWorker.addEventListener('controllerchange', () => {
        if (!refreshedPage) {
          refreshedPage = true;
          window.location.reload();
        }
      });
    });
  }
</script>
```

So it appears that the backend service worker is being correctly referenced over http, while the front-end worker is being incorrectly referenced over https (since I'm on localhost without ssl).

**Comment by su-narthur** [comment]
@westonruter And... found the code responsible:

pwa/wp-includes/service-workers.php:97

```
	if ( WP_Service_Workers::SCOPE_FRONT === $scope ) {
		return add_query_arg(
			array( WP_Service_Workers::QUERY_VAR => $scope ),
			home_url( '/', 'https' )
		);
	} else {
		return add_query_arg(
			array( 'action' => WP_Service_Workers::QUERY_VAR ),
			admin_url( 'admin-ajax.php' )
		);
	}
```

`home_url` is specifying the scheme while `admin_url` is not. Is there any reason the scheme shouldn't be removed from the `home_url` call?

**Comment by westonruter** [comment]
@su-narthur The only reason I think is supporting HTTP localhost wasn't on our radar when developing. I suggest stripping off the protocol entirely from the URL, both for the front and admin service workers. The relative scheme will then inherit the scheme of the page. If the page is not HTTPS then the browser will reject for non-localhost URLs automatically.

**Comment by westonruter** [comment]
@su-narthur In other words, could you give this a try:

```diff
--- a/wp-includes/service-workers.php
+++ b/wp-includes/service-workers.php
@@ -92,16 +92,18 @@ function wp_get_service_worker_url( $scope = WP_Service_Workers::SCOPE_FRONT ) {
 	}
 
 	if ( WP_Service_Workers::SCOPE_FRONT === $scope ) {
-		return add_query_arg(
+		$url = add_query_arg(
 			array( WP_Service_Workers::QUERY_VAR => $scope ),
 			home_url( '/', 'https' )
 		);
 	} else {
-		return add_query_arg(
+		$url = add_query_arg(
 			array( 'action' => WP_Service_Workers::QUERY_VAR ),
 			admin_url( 'admin-ajax.php' )
 		);
 	}
+
+	return preg_replace( '#^https?:(?=//)#', '', $url );
 }
 
 /**
```

If it works, would you open a PR?
