### ISSUE TITLE
Document the current state of app shells

### ISSUE THREAD

**Issue by postphotos** [xwp/pwa-wp#12]
As a WordPress developer, I should be able to leverage the PWA app shell feature.

AC1: Document and describe, if used, app shells from the discovery in #2 .
(AC2 moved to its own issue: #22)

**Comment by miina** [comment]
Started looking into AC1 -- plugins using app shell from discovery within #1.

**Comment by miina** [comment]
One plugin that seems to be described as having shell features seems to be [Offline Shell](https://wordpress.org/plugins/offline-shell/) plugin.

According to the description and based on the admin interface and settings, the plugin registers a service worker that caches theme assets and files, it's possible to choose from the plugin settings which files to cache. Content is not cached for offline reading, there are no modifications made to any  of the cached files, just the templates seem to be decoupled from the content.
If I understood correctly.

**Comment by kienstra** [comment]
Hi @postphotos,
Sorry to nitpick, but maybe the title here could also mention AC2 (Prototype a usage of app shells).

**Comment by westonruter** [comment]
AMP is going to play an important role here, and it facilitates a lot for doing PWA already: https://www.ampproject.org/docs/integration/pwa-amp/amp-in-pwa

See also the feature request for seamless page transitions: https://github.com/ampproject/amphtml/issues/12981. If AMP is already a baseline requirement for being able to embed content inside an SPA, then we could defer to AMP for a component that provides guiderails for how an app shell is implemented. Before such an AMP component is available, we cannot serve an app shell _as_ an AMP document and instead must use the AMP Shadow API to render the AMP document inside of the non-AMP PWA document.

Also, @danielbachhuber pointed out to me a JS library that has a lot of overlap with the kind of functionality we'd be looking to realize here: http://barbajs.org/

**Comment by westonruter** [comment]
I think the challenge for using AMP Shadow API with WordPress in an app shell is that WordPress themes render the shell as part of the template no just the content. So I see that as being a challenge: figuring out a way to extract `<div id=content>` from a response, along with any styles that target the contents inside of it, and use it as a standalone document for a shadow root.

**Comment by westonruter** [comment]
If the AMP plugin is indeed a prereq then we have the capability, since we have the DOM and the parsed CSS which we can use to dynamically generate pages from WordPress templates without the shell.

**Comment by kevincoleman** [comment]
This issue is being split out to #12 (documentation/research) and #22 (prototyping).

**Comment by miina** [comment]
@westonruter Can this issue be closed?
