### ISSUE TITLE
Update Workbox to 4.0.0-beta.1

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#120]
See https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0-beta.1

**Comment by swissspidy** [comment]
Workbox v4.0.0-rc.0 is now out: [GoogleChrome/workbox@`v4.0.0-rc.0` (release)](https://github.com/GoogleChrome/workbox/releases/tag/v4.0.0-rc.0)

**Comment by westonruter** [comment]
Yes. I should have closed this issue before since the update to beta already happened. For rc see https://github.com/xwp/pwa-wp/pull/136
