### ISSUE TITLE
Which security headers to set for wp.serviceworker?

### ISSUE THREAD

**Issue by nisbet-hubbard** [xwp/pwa-wp#1201]
Workers are considered to have their own execution context and not governed by the content security policy of the HTML.

I’m wondering what CSP and other security headers (eg Referrer-Policy) you would recommend for it?

**Comment by westonruter** [comment]
I'm actually not familiar with the specifics for CSP and workers, so I don't have any recommendations. But I relayed your question to Gemini. Maybe its response will be helpful: https://g.co/gemini/share/5e1170cafaea
