### ISSUE TITLE
Known issue with video

### ISSUE THREAD

**Issue by alexlii1971** [xwp/pwa-wp#126]
Hello,

According to the author of Super Progressive Web Apps, there is a Know issue for iOS:

https://wordpress.org/support/topic/it-will-cause-issue-media-error-formats-not-supported-or-sources/

According the post, it is closely related to service worker on PWA,

But I did not found the issue at https://github.com/xwp/pwa-wp/issues

will the issue be happened “PWA”(this plugin) please?

Thanks in advance, and have a nice day.

**Comment by westonruter** [comment]
I'm not sure. The plugin does not do anything with video by default. It's really up to you for how you want to register routes and whether you want to cache videos at all.
