### ISSUE TITLE
"Corrupted Content Error" in Firefox

### ISSUE THREAD

**Issue by aristath** [xwp/pwa-wp#133]
Using the latest master branch, I'm getting this on a testsite:
![screenshot from 2019-02-05 12-38-08](https://user-images.githubusercontent.com/588688/52267967-08e0ab00-2943-11e9-96bc-938c500ff48d.png)

In the console in firefox I see this error:
`Failed to load ‘https://avadatest.theme-fusion.com/ari/’. A ServiceWorker passed a promise to FetchEvent.respondWith() that rejected with ‘TypeError: class constructors must be invoked with |new|’.`

The line referenced in the error is this:
`const navigationCacheStrategy = wp.serviceWorker.strategies[ "NetworkOnly" ]( ( function() {const strategyArgs = {};strategyArgs.plugins = [];return strategyArgs;} )() );`
so it looks like this is it: https://github.com/xwp/pwa-wp/blob/641b8319c2d8aa91a1058e2d1376170a57f9b43f/wp-includes/js/service-worker-navigation-routing.js#L139
adding `new` in there seems to have fixed the issue on Firefox.

**Comment by westonruter** [comment]
This is something I missed in #127.
