### ISSUE TITLE
Error templates being returned with status code 404, preventing service worker installation

### ISSUE THREAD

**Issue by narthur** [xwp/pwa-wp#144]
I'm trying to use the plugin on a staging server, but this issue is preventing the service workers from being updated properly.

Basically workbox tries to cache `?wp_error_template=offline` and `?wp_error_template=500`. The server returns the templates correctly, except that they're returned with a status code of 404, causing workbox to error out. When I load these templates locally, they are returned with a status code of 200, so the service workers are updated successfully.

This is the error I see in the console in staging:

```
logger.mjs:44 workbox Service worker installation failed. It will be retried automatically during the next navigation.
print @ logger.mjs:44
(anonymous) @ logger.mjs:57
(anonymous) @ precache.mjs:49
Promise.catch (async)
(anonymous) @ precache.mjs:46
PrecacheController.mjs:194 Uncaught (in promise) bad-precaching-response: The precaching request for 'https://[domain]/?wp_error_template=offline&__WB_REVISION__=0.2-alpha1%3Btwentyseventeen%3D2.1%3Buser%3D1%3Boptions%3D7a4128790238a92c1876fec09204964a%3Bnav%3D1f9bfa57d90fc8fdcd75324abef655a6%3Bdeps%3De0bce031546dd87d52c1124f00b82494%3Bc2ae72a5f994c1bd83d7066ce06a0964' failed with an HTTP status of 404.
    at PrecacheController._addURLToCache (https://[domain]/wp-content/plugins/pwa/wp-includes/js/workbox/workbox-precaching.dev.js:445:15)
    at async Promise.all (index 0)
    at async PrecacheController.install (https://[domain]/wp-content/plugins/pwa/wp-includes/js/workbox/workbox-precaching.dev.js:352:7)
```

Visually, the templates are identical between localhost and staging. The only thing different I can see is the status code.

How can I resolve this such that the templates are returned with status 200 on staging like they are locally, so that they can be successfully precached?

**Comment by westonruter** [comment]
@narthur Can you debug where `status_header()` is being called to see who is sending the 404 status? Is it `\WP::handle_404()`? 

Does your staging server not have any posts on it? That could be why. One of the conditions for sending the 404 status is if `$wp_query->posts` is empty.

You may have identified an improvement, where `pre_handle_404` should be getting filtered to never return `true` when the `wp_error_template` query var is present.

**Comment by narthur** [comment]
@westonruter It appears your hypothesis was correct. I threw an exception inside `status_header()` to get a stack trace:

```
<br />
<b>Fatal error</b>:  Uncaught Exception in /home/audiove9/public_html/dev/wp-includes/functions.php:1218
Stack trace:
#0 /home/audiove9/public_html/dev/wp-includes/class-wp.php(720): status_header(404)
#1 /home/audiove9/public_html/dev/wp-includes/class-wp.php(740): WP-&gt;handle_404()
#2 /home/audiove9/public_html/dev/wp-includes/functions.php(1105): WP-&gt;main('')
#3 /home/audiove9/public_html/dev/wp-blog-header.php(16): wp()
#4 /home/audiove9/public_html/dev/index.php(17): require('/home/audiove9/...')
#5 {main}
  thrown in <b>/home/audiove9/public_html/dev/wp-includes/functions.php</b> on line <b>1218</b><br />
```

Line 720 of `class-wp.php` is indeed a call to status_header, throwing a 404 if no posts were found previously in the function.

Adding a post causes the templates to be returned with a status code of 200, workbox successfully precaches them, and the service workers seem to install successfully.

**Comment by westonruter** [comment]
@narthur Awesome. Thank you for confirming that. Would you please test #145?

**Comment by narthur** [comment]
@westonruter Done. :)
