### ISSUE TITLE
Undefined index: short_name

### ISSUE THREAD

**Issue by iandunn** [xwp/pwa-wp#168]
`Notice: Undefined index: short_name in wp-content/plugins/pwa/wp-includes/class-wp-web-app-manifest.php on line 77` 

`get_manifest()` doesn't supply a default short name. When `$manifest['name']` is `WordCamp.test`, `$short_name_matches` is an empty array.

Maybe it should default to `substr( $manifest['name'], 0, 12 )` as a safety measure? Or maybe the regex can be made to guarantee a value?

**Comment by westonruter** [comment]
Good catch, this logic is not ensuring a `short_name` is defined:

https://github.com/xwp/pwa-wp/blob/24e78a656398b16bb3bc2baf797dc8c6ef060e0b/wp-includes/class-wp-web-app-manifest.php#L129-L140

And this causes the undefined index on:

https://github.com/xwp/pwa-wp/blob/24e78a656398b16bb3bc2baf797dc8c6ef060e0b/wp-includes/class-wp-web-app-manifest.php#L77-L78

Originally the `short_name` was not being read from anywhere, and so this was why there was no fallback. But in #129 then it was being added in those `meta` tags, causing the undefined indexes.

**Comment by westonruter** [comment]
According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Manifest/short_name):

> The short_name member is a string that represents the name of the web application displayed to the user if there is not enough space to display name (e.g., as a label for an icon on the phone home screen)

I think the `meta` tags should just be updated to use the `name` when `short_name` is absent.

**Comment by iandunn** [comment]
👍 thanks!
