### ISSUE TITLE
Evaluate and document existing service worker implementations in WordPress

### ISSUE THREAD

**Issue by postphotos** [xwp/pwa-wp#2]
**As a developer in the WordPress ecosystem and as a contributor to this project, I should have an understanding  of the complex usage of service workers used today before we propose a solution.**

- [x] AC1: Record what plugins, themes and headless projects we can find that are using service workers, sharing any quirks and oddities and lessons learned along the way.
- [ ] AC2: Commonalities to pain points should recorded and brought to product definition.

Document of plugins to review that use service workers: https://docs.google.com/document/d/1bTgRGyQiGUHm-0yG8LWkKAJ_heLxeLS7BKcfI2SON84/edit#

**Comment by postphotos** [comment]
A useful doc that helps with the initial effort (via @westonruter) has already been generated:
https://docs.google.com/document/d/1bTgRGyQiGUHm-0yG8LWkKAJ_heLxeLS7BKcfI2SON84/edit

**Comment by kienstra** [comment]
**Working On This**

I'm working on this, starting at the top of the "WordPress.org Plugins" [list](https://docs.google.com/document/d/1bTgRGyQiGUHm-0yG8LWkKAJ_heLxeLS7BKcfI2SON84/edit
). Like we talked about, anyone is free to work starting from the last item in the list.

**Comment by kienstra** [comment]
**Plugins 1-12 Analyzed**

On [this list](https://docs.google.com/document/d/1bTgRGyQiGUHm-0yG8LWkKAJ_heLxeLS7BKcfI2SON84/edit?usp=sharing
), I analyzed the WordPress.org plugins 2 and 4-12.

**Comment by miina** [comment]
Started going through the plugins starting from the last item in the WordPress plugins' list (34).

**Comment by miina** [comment]
WordPress.org plugins list is now analyzed and [the document](https://docs.google.com/document/d/1bTgRGyQiGUHm-0yG8LWkKAJ_heLxeLS7BKcfI2SON84/edit) updated according to findings.

**Comment by kevincoleman** [comment]
Having had a group review of our findings here, this appears to be mostly complete.

@postphotos and I have spent some time with our notes from the review, and @postphotos is adding issues from those points.

What do we need on this to consider it finished?

**Comment by kienstra** [comment]
**Probably Finished**

Hi @kevincoleman,
Good question, I think AC1 is complete, with the analysis in [this document](https://docs.google.com/document/d/1bTgRGyQiGUHm-0yG8LWkKAJ_heLxeLS7BKcfI2SON84/edit#).

And it sounds like you and @postphotos applied AC2:
>Commonalities to pain points should recorded and brought to product definition.

**Comment by kevincoleman** [comment]
Great! Thanks @kienstra. I’ll go ahead and consider this done. If we want to revisit the findings to create more issues, we know where to find it.

**Comment by igrigorik** [comment]
Great work on the audit! Squinting, there's definitely a visible pattern of duplicated work across a number of these plugins — e.g. push notifications! Enabling this in core would be a nice win.
