### ISSUE TITLE
Short Name empty

### ISSUE THREAD

**Issue by goaround** [xwp/pwa-wp#200]
I have a problem with the Regex used here to shorten the page name: https://github.com/xwp/pwa-wp/blob/8fbaf8b928f60aaf7477e2fdae7e19baae55f0cf/wp-includes/class-wp-web-app-manifest.php#L139

My domain name is exacly 12 characters long, following by a dot TLD: "Travel-Dealz.de". "Travel-Dealz" would be a beautiful shortname but because the Regex `/^.{0,12}(?= |$)/` only looks for spaces, my short_name is completly emtpy: https://regexr.com/4i7mt

My proposal is to look for spaces and dots: `/^.{0,12}(?=[ .]|$)/` see here https://regexr.com/4i7mq

**Comment by westonruter** [comment]
Yeah, I think we should just eliminate trying to automatically derive a `short_name`. It should be supplied via filter instead. Please take a look at #181 and see if you agree.

**Comment by goaround** [comment]
Is there really a limit of 12 chars? I use the filter too and think its better to eliminate the regex.

**Comment by westonruter** [comment]
There is no hard limit on 12 characters, as far as I know. The limit is just to be short enough to fit with an icon.

Ref. https://developer.mozilla.org/en-US/docs/Web/Manifest/short_name

**Comment by westonruter** [comment]
Actually, Chrome recommends a 12 character limit for short_name: https://developer.chrome.com/apps/manifest/name#short_name

But it isn't reliable to compute this automatically, so let's get rid of it. It should only be supplied by a site explicitly.

**Comment by westonruter** [comment]
I've opened a PR to remove it: #201
