### ISSUE TITLE
admin_title filter called without ensuring current_screen is set

### ISSUE THREAD

**Issue by rrennick** [xwp/pwa-wp#206]
In /wp-admin/error.php, the `admin_title` filter is used without ensuring that the current_screen is set: https://github.com/xwp/pwa-wp/blob/7cf111f43dff028d6331009eabdc25848e6cd44f/wp-admin/error.php#L45

admin-header.php does this with https://github.com/WordPress/WordPress/blob/master/wp-admin/admin-header.php#L29:L32

before using the filter in https://github.com/WordPress/WordPress/blob/master/wp-admin/admin-header.php#L68.

This is causing the fatal error reported in https://github.com/woocommerce/woocommerce-admin/issues/2732 .

**Comment by westonruter** [comment]
@rrennick Can you confirm that #207 fixes the problem for you?

**Comment by rrennick** [comment]
> Can you confirm that #207 fixes the problem for you?

It does.
