### ISSUE TITLE
How to properly handle nonce caching?

### ISSUE THREAD

**Issue by LukaszJaro** [xwp/pwa-wp#237]
Hi,

I have a contact form that uses a nonce, when the nonce expires it stays in the cache unless page reload occurs. Since the nonce value is stale and no longer valid, it causes the form to fail. Is there a filter for specific nonce exclusion?

**Comment by westonruter** [comment]
That's a good question. What caching strategy are you using for pages?

**Comment by LukaszJaro** [comment]
STRATEGY_STALE_WHILE_REVALIDATE

```
add_filter(
	'wp_service_worker_navigation_caching_strategy',
	function() {
		return WP_Service_Worker_Caching_Routes::STRATEGY_STALE_WHILE_REVALIDATE;
	}
);

add_filter(
	'wp_service_worker_navigation_caching_strategy_args',
	function( $args ) {
		$args['cacheName']                           = 'pages';
		$args['plugins']['expiration']['maxEntries'] = 20;
		return $args;
	}
);
```

**Comment by westonruter** [comment]
OK, thank you. Yes, I can definitely see how this would be problem. One possibility would be to make pages expire within the lifespan of the nonce. This can be done using `maxAgeSeconds`,  ror example:

```php
add_filter(
	'wp_service_worker_navigation_caching_strategy_args',
	function( $args ) {
		$args['cacheName']                           = 'pages';
		$args['plugins']['expiration']['maxEntries'] = 20;

		// 👇 New!
		/** This filter is documented in wp-includes/pluggable.php */
		$max_age_seconds = apply_filters( 'nonce_life', DAY_IN_SECONDS );
		$args['plugins']['expiration']['maxAgeSeconds'] = $max_age_seconds;

		return $args;
	}
);
```

The value and applied filter there is copied from [`wp_nonce_tick()`](https://developer.wordpress.org/reference/functions/wp_nonce_tick/) in core.

**Comment by LukaszJaro** [comment]
Brilliant, thanks! I'm going to give this a shot

**Comment by LukaszJaro** [comment]
Thanks @westonruter ! That seemed to do it, no issues so far. Looking forward to the new plugin version!

**Comment by westonruter** [comment]
Added this guidance to the new wiki page: https://github.com/GoogleChromeLabs/pwa-wp/wiki/Service-Worker
