### ISSUE TITLE
Investigate solutions for HTTPS detection and upgrading

### ISSUE THREAD

**Issue by kienstra** [xwp/pwa-wp#24]
**As XWP proposing solutions for ease of PWA adoption, we need to understand what challenges exist in HTTPS compatibility, whether the solutions are good enough for ease of use and decide if and where to extend the current solutions and approaches to make it easier to migrate a WordPress website from HTTP to HTTPS/HSTS.**

- [x] AC1: Investigate existing solutions for HTTPS detection, including insecure content and requests
- [x] AC2: Investigate existing UX for HTTPS upgrades
- [x] AC3: Look at the [upgrade-insecure-requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests) directive as mentioned by @westonruter 
- [x] AC4: Look at which solutions are widely used and supported by WordPress, understand their utility and see if there any action steps by our project.

Currently blocks #17.

**Comment by kienstra** [comment]
Here's the beginning of the [discovery document](https://docs.google.com/document/d/1hkyc-GEq60PXMI4wd7NNnNO3gu6aWhZK4HRsDlynH_I/edit?usp=sharing).

**Comment by postphotos** [comment]
Hi @kienstra, thanks for creating this issue! I updated the original post with a user story as well.

**Comment by kienstra** [comment]
**Discovery Document Ready**

Hi @westonruter and @postphotos,
This [discovery document](https://docs.google.com/document/d/1hkyc-GEq60PXMI4wd7NNnNO3gu6aWhZK4HRsDlynH_I/edit?usp=sharing) details some existing HTTPS solutions in [WordPress.org plugins](https://docs.google.com/document/d/1hkyc-GEq60PXMI4wd7NNnNO3gu6aWhZK4HRsDlynH_I/edit#heading=h.w3u34ghyxubs) and [header values](https://docs.google.com/document/d/1hkyc-GEq60PXMI4wd7NNnNO3gu6aWhZK4HRsDlynH_I/edit#heading=h.hxc184kp2gwj).

And it has some [suggestions](https://docs.google.com/document/d/1hkyc-GEq60PXMI4wd7NNnNO3gu6aWhZK4HRsDlynH_I/edit#heading=h.scpi2els0qf) for how we might emulate them.

To edit this, feel free to request access.

**Comment by kienstra** [comment]
**Thanks!**

Hi @postphotos,
Thanks for your good points.

1. Good idea to use `upgrade-insecure-requests`. What do you think of [this possible UI](https://github.com/xwp/pwa-wp/issues/17#issuecomment-404287974) that has a checkbox for it?

>I most worry about the user who, assuredly, will get lost or overwhelmed along the way.

That's a good point. Searching for mixed content is probably going to confuse people. Maybe there could be a recommendation in the [proposed UI](https://github.com/xwp/pwa-wp/issues/17#issuecomment-404287974). Like if there's only passive insecure content found, we don't recommend that they use `upgrade-insecure-requests`.

**Comment by kienstra** [comment]
**Closing, Moving Discussion To #17**

Hi @postphotos,
If it's alright, I'm going to close this. Could we move the discussion to the solution in #17?
