### ISSUE TITLE
Unregister unused ServiceWorker scopes

### ISSUE THREAD

**Issue by nico-martin** [xwp/pwa-wp#26]
By design, once you register a ServiceWorker it stays registered untill you unregister it.
Now since we have the ServiceWorker API we update an active ServiceWorker based on the Scope on each pageload.
Code that is not longer in use will be removed once the ServiceWorker updates (so on every pageload). Thats good.

But what if a plugin uses a special scope? Once the plugin is disabled, the registration/update method won't be included anymore and the ServiceWorker will still be active in browsers that visited the page when the plugin was active.

Should we add an unregister method for all ServiceWorker/Scopes that have ever been registered?

**Comment by westonruter** [comment]
Good point. At the moment when there are no scripts registered for a given scope the PR #14 will return a 404 response. What if instead it served a service worker that [unregistered itself](https://github.com/NekR/self-destroying-sw) instead?

**Comment by nico-martin** [comment]
The problem is if there are no scripts for a given scope, the scope won't even be registered. So there shouldn't even be a request at all. But since there was one some time before it still lives in the browser.
My idea would be to have a wp_option with all ever registered scopes. And then, after all current scopes are registered you compare those scopes with the registered scopes from the option an call an unregister method for scopes that are not longer active.

**Comment by nico-martin** [comment]
This might seem a bit ugly, but I don't expect that to happen very often..

**Comment by westonruter** [comment]
I wonder if we really need to allow arbitrary scopes to be registered, actually. Maybe there should just be one service worker scope for the fronted and another for the wp-admin. Why would there need to be more scopes than these two?

**Comment by nico-martin** [comment]
Good point. I always thought you had a strong reason for this feature.

I also think this is more a general problem with PWA/ServiceWorker. Lets say you relaunch your PWA you need to unregister every ServiceWorker you ever used because they could coflict with you current ServiceWorker.
@amedina , do you know if the chrome-team is aware of this and if they are working on something?

**Comment by westonruter** [comment]
Inquired about WordPress use cases for multiple scopes at https://core.trac.wordpress.org/ticket/36995#comment:18

**Comment by westonruter** [comment]
@nico-martin Please review https://github.com/xwp/pwa-wp/pull/27
