### ISSUE TITLE
PWA 'pages' should set meta robots indexing directives

### ISSUE THREAD

**Issue by jonoalderson** [xwp/pwa-wp#300]
Requests which return service worker 'pages' or content - like `example.com/?wp_service_worker=1`, `example.com/?wp_error_template=offline` and `example.com/?wp_error_template=500` (and any other/similar responses) - should indicate that they shouldn't be indexed by search engines or social media.

This can be achieved by returning an `x-robots-tag` HTTP header with such responses, with a value of `noindex, follow`.

**Comment by westonruter** [comment]
Good point. Given the current codebase, this can be done via:

```diff
--- a/wp-includes/general-template.php
+++ b/wp-includes/general-template.php
@@ -111,6 +111,7 @@ function wp_add_error_template_no_robots() {
 function wp_unauthenticate_error_template_requests() {
 	if ( is_offline() || is_500() ) {
 		wp_set_current_user( 0 );
+		add_action( 'wp_head', 'wp_no_robots' );
 	}
 }
``` 

However, we may want to rename `wp_unauthenticate_error_template_requests()` to be more appropriate.

**Comment by westonruter** [comment]
Hold on. Is this not already being done? See this code:

https://github.com/GoogleChromeLabs/pwa-wp/blob/77c09444cee70f359ae82ee537bbf7c1a190ef34/wp-includes/general-template.php#L90-L101

**Comment by westonruter** [comment]
Is not the `meta` tag equivalent to an `X-Robots-Tag` HTTP response header?

**Comment by jonoalderson** [comment]
Yep, that's indeed equivalent. Good catch; I was checking HTTP headers but neglected to check the HTML source... Oops!

**Comment by jonoalderson** [comment]
Just looks like we're missing the x-robots-tag output on `?wp_service_worker=1`, then.

**Comment by westonruter** [comment]
Why is it needed for the service worker script? Other scripts served by WordPress don't have that header (e.g. jQuery).

**Comment by jonoalderson** [comment]
(most) other scripts are obviously scripts (e.g., ending in `.js`), and, exist as real files (which we can't intercept via WordPress),

**Comment by westonruter** [comment]
Right, but is it necessary? Do any search engines index JS assets?

**Comment by jonoalderson** [comment]
They may do, if they don't realise that they're JS assets. 

This isn't the only use-case, too. Anecdotally, I'm currently dabbling with setting various HTTP headers on different templates/pages (mostly for preloading/pushing resources), and there's no 'clean' way to exclude service worker results pages.

People are going to continually run into this kind of problem, whilst we have a dynamically generated/served JavaScript file which presents as a page. The situation isn't radically different from `is_robots()`. Some simple wrappers for conditional logic here will make managing this much easier.

**Comment by westonruter** [comment]
Sorry for the long pause.

> They may do, if they don't realise that they're JS assets.

Note that in #289 the URL for service workers will be `/wp.serviceworker` as opposed to `/?wp_service_worker=1`. So there will be less potential confusion. 

In any case, the `Content-Type` is `text/javascript`. If they can't realize that it is a JS asset from this, then I'd consider that to be a horrible search engine 😄 

In any case, I've opened a PR to add this response header: #330.

**Comment by jonoalderson** [comment]
Well, undeclared file types also leave other systems blind, so it's best practice for a 'non-page' asset to declare its type in the URL. Cloudflare, for example, only caches (by default) assets based on their file extension; regardless of the `Content-Type` header.

**Comment by westonruter** [comment]
It's not feasible to for a WP-generated file to end in `.js` unfortunately given that many server configurations will send the request straight to the filesystem. See discussion at https://github.com/GoogleChromeLabs/pwa-wp/issues/287#issuecomment-642838589.

**Comment by jonoalderson** [comment]
Yeah, I caught that. I really like `.serviceworker` as a graceful workaround!
