### ISSUE TITLE
Facilitate indicating the site icon as being maskable

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#304]
As reported on the [support forum](https://wordpress.org/support/topic/manifest-doesnt-have-a-maskable-icon-3/), when doing a Lighthouse PWA audit, the web app manifest generated by the plugin currently gets a warning:

> ![Manifest doesn't have a maskable icon](https://user-images.githubusercontent.com/134745/86538881-a11eee80-bead-11ea-80ec-5743e75d5347.png)

Read more about this on web.dev: [Manifest doesn't have a maskable icon](https://web.dev/maskable-icon-audit/).

A site owner can fix this problem by just adding the `purpose` property to all of the icons:

```php
add_filter( 'web_app_manifest', function( $manifest ) {
	$manifest['icons'] = array_map(
		function ( $icon ) {
			if ( ! isset( $icon['purpose'] ) ) {
				$icon['purpose'] = 'any maskable';
			}
			return $icon;
		},
		$manifest['icons']
	);
	return $manifest;
} );
```

The plugin could also automatically add this `maskable` property. But these both assume that the icon is actually maskable. Is this good to assume? What if we added a new checkbox after where the Site Icon is supplied in the Customizer to let the user indicate it is maskable:

![image](https://user-images.githubusercontent.com/134745/86539125-1808b700-beaf-11ea-9625-48e6154423c4.png)

Related: #246

**Comment by fellyph** [comment]
I saw this same issue this weekend using chrome canary, if there is no customisation on the panel should it include it maskable by default?

**Comment by westonruter** [comment]
I don't think it should be maskable by default because then it could crop the icon undesirably.

**Comment by fellyph** [comment]
You are right, the checkbox is the best option.

**Comment by valendesigns** [comment]
There should probably be an explanation of what it means to be maskable. I could see regular users having very confused looks on their face while viewing this option.

**Comment by crm911** [comment]
//A site owner can fix this problem by just adding the purpose property to all of the icons://

Sorry, I am not a developer. Where exactly does that go? Somewhere inside pwa_manifest.json?

**Comment by westonruter** [comment]
It can go in your theme's `functions.php` file.

**Comment by crm911** [comment]
Thank you. This did it for me.

A tip for others - always flush the cache. :)

**Comment by waybis** [comment]
I tried this, adding 20% padding around the icon to make it maskable and added the filter and verified the manifest updated which shows "any maskable". 

What I'm seeing on desktop bookmark favicon and android 10 (Moto G7) homescreen icon and favicon is a reduced sized icon with a white ring around it.  Before this, it was full size with transparent background.

However it passes with the Lighthouse PWA audit! I've also tested the icon on maskable.app and it fits perfectly inside the Minimum safe area.  I tried transparent and white backgrounds but each make no difference to the size.  

Any suggestions?

**Comment by vralle** [comment]
```php
add_filter(
	'web_app_manifest',
	function( $manifest ) {
		$manifest['icons'] = array(
			array(
				'src'   => '/favicon-192.png',
				'sizes' => '192x192',
				'type'  => 'image/png',
			),
			array(
				'src'   => '/favicon-512.png',
				'sizes' => '512x512',
				'type'  => 'image/png',
			),
			array(
				'src'     => '/favicon-maskable-192.png',
				'sizes'   => '192x192',
				'type'    => 'image/png',
				'purpose' => 'maskable',
			),
			array(
				'src'     => '/favicon-maskable-512.png',
				'sizes'   => '512x512',
				'type'    => 'image/png',
				'purpose' => 'maskable',
			),
		);

		return $manifest;
	}
);

```

**Comment by westonruter** [comment]
~This is a bit more complicated now with Full Site Editing because the Site Icon is now managed in the Block Editor, not the Customizer.~

Update: Per below in https://github.com/GoogleChromeLabs/pwa-wp/issues/304#issuecomment-1034144550 I think we should skip any FSE-specific integration for now given the Customizer is still linked to for setting the Site Icon.

**Comment by westonruter** [comment]
This is something else that comes up over and over again, so we need a UI to indicate the icon is maskable. If not using a block-based theme, the Site Icon control in the Customizer is where the UI should live per my screenshot above. Otherwise, if using a block-based theme when the Customizer is not available, I'm not entirely clear where the UI should be located. I suppose it would be an extension to the Site Logo block?

**Comment by thelovekesh** [comment]
@westonruter I have taken this up. Related to the scenario of issue I and @ankitrox discussed the possibilities to make this fully compatible in FSE. Here are some key points from the discussion:

*Customizer*

- Implement a checkbox for the maskable icon option in the customizer.
- Add a link about - what is maskable icon.
- Check if the icon is set, the size of the icon, MIME type, and if it is maskable. #229
- If any of the above criteria is not met, show a warning to the user.
- Usage of `web_app_manifest` hook to add purpose in the manifest.


*FSE*

- Target block will be the Site Logo block.
- Check if the user has enabled `Use as site icon` toggle.
- If yes, then show the toggle for the maskable icon.
- While saving the block set we will also save it for customizer as this icon will also be saved for customizer setting.

**Comment by westonruter** [comment]
> When the checkbox for maskable icon

It would be a nice touch if clicking this checkbox would apply a mask to the icon so the user can see what effect it has. This would in part limit the need for having a link to explain what maskable icons are.

> * While saving the block set we will also save it for customizer as this icon will also be saved for customizer setting.

I'm not too familiar with how FSE site icon is managed. The non-FSE Custom Logo is stored as a `theme_mod` and the Customizer saves it as such. In contrast, the Site Icon is stored as an `option`. I recall that in FSE the Custom Logo is now stored as an option instead. It's not clear to me how the Custom Logo, however, maps to the Site Icon in FSE. In particular, the logo may be completely inappropriate for use as an icon. The logo may be rectangular and be visually rich, whereas a site icon needs to be square and able to be legible at very small sizes. It also needs to be a PNG, as you noted. 

In looking further, I saw the [WP Tavern article](https://wptavern.com/customizer-will-disappear-for-some-block-theme-users-with-wordpress-5-9) about this and:

> If they are different images or if the user does not use a logo, the only built-in way to change the site icon directly is through the `customize.php` URL trick mentioned above. The Site Logo block also adds a link to the customizer option. 

<img width="365" alt="image" src="https://user-images.githubusercontent.com/134745/153280501-9833b443-d866-47f7-b101-fb1d8821e286.png">

So the ability to set the maskable flag would still be available for FSE themes, if they click that “Site Icon settings” link. To me it seems like there should be a non-Customizer way to set the Site Icon when using FSE. 

All this to say: I think it's probably good to just skip the FSE integration for now, given that the user can (and probably should) use the Customizer for this. Presumably the UI for managing the Site Icon will evolve in the FSE Site Editor, so probably best to not spend too much time on it right now.

**Comment by ankitrox** [comment]
> It would be a nice touch if clicking this checkbox would apply a mask to the icon so the user can see what effect it has. This would in part limit the need for having a link to explain what maskable icons are.

Currently when we upload icon, it is already rounded corner giving the impression that it is masked. If we apply above-mentioned strategy, we may need to make the icon square shaped by default. When checkbox for maskable icon is checked, we can add border-radius to icon.

Does this sound fine @westonruter ?

**Comment by westonruter** [comment]
The rounded corners are good, but they're not round enough. It should instead apply the “minimum safe zone” as described at https://web.dev/maskable-icon/#are-my-current-icons-ready

**Comment by thelovekesh** [comment]
@westonruter Showing icon in `minimum safe zone` when checking `Maskable icon` will work and the user can have an Idea when to use this setting. Check the below demos and let me know if it works.

https://user-images.githubusercontent.com/54371619/153477615-1493fce6-a4c8-411c-a1f0-188218a649bf.mp4

https://user-images.githubusercontent.com/54371619/153478117-59901b5c-b307-4c69-a38e-c37b836329c6.mp4

**Comment by westonruter** [comment]
Yes, that looks good!

**Comment by pooja-muchandikar** [comment]
@thelovekesh 

Following are some observations related to Site Icon being Maskable. 

- Maskable checkbox is in place but when the checkbox is checked from customizer, an error is shown on manifest, ideally it should show any error. Also the same error is displayed twice any reason?
![image](https://user-images.githubusercontent.com/41000648/163953764-8feef948-d6e9-4142-a433-6445063ab64b.png)

![image](https://user-images.githubusercontent.com/41000648/163953727-2a698cea-8f79-4e71-a9e4-ea37a6ff0d8d.png)

---

- If site icon is not set, `Maskable Icon` setting is visible, it shouldn't be visible. It should be visible only if site icon is set
![image](https://user-images.githubusercontent.com/41000648/163954774-a6839a6f-41ee-421f-b204-d8c80a201baa.png)

---

- If Site icon was set and set as maskable and then removed the site icon, `Maskable Icon` setting remains checked. 

https://user-images.githubusercontent.com/41000648/163956289-0bdc79d6-c31c-4aa3-8427-52528a86e664.mp4

---

```
Test Environment
WordPress v5.9.3
PWA v0.7.0-alpha-52d5096-20220419T054300Z
Theme 2021
```

cc: @westonruter

**Comment by westonruter** [comment]
> * Maskable checkbox is in place but when the checkbox is checked from customizer, an error is shown on manifest, ideally it should show any error.

Very interesting. I hadn't seen this warning before. I see it also reported here:

- https://github.com/onderceylan/pwa-asset-generator/issues/679 and https://github.com/onderceylan/pwa-asset-generator/issues/778
- https://github.com/SuperPWA/Super-Progressive-Web-Apps/issues/237

In the latter case, the fix was just to duplicate the icon and give one `maskable` and the other `any`: https://github.com/SuperPWA/Super-Progressive-Web-Apps/pull/238/commits/ca128daf49d322719b42828e40c3e8763205616d

But this presumes that the chosen icon actually is suitable for masking and non-masking. If we want to be extra sure for the user, we could duplicate the preview image to appear alongside the checkbox and only show it and give it a masking when the checkbox is selected, leaving the original preview as-is without any masking. But that may be excessive. In general I'd think that if an icon is maskable then it should be presumed to work without masking as well.

> * If Site icon was set and set as maskable and then removed the site icon, `Maskable Icon` setting remains checked.

Yes, it makes sense that the field should be hidden when no icon is selected. Good catch.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

Reference: https://github.com/GoogleChromeLabs/pwa-wp/pull/770#issuecomment-1108070092
