### ISSUE TITLE
Lighthouse issue with no Maskable Icon

### ISSUE THREAD

**Issue by austintude** [xwp/pwa-wp#313]
After updating the functions.php to address the short_name error, I reran the Lighthouse extension and discovered a 'new to me' error as regards the PWA portion.
It reads "Manifest doesn't have a maskable icon".
I'm not certain how to introduce this feature without also hard-coding it into the functions.php file.
Is there an alternative solution to this issue?
The sites I am testing this with are https://austintatiousdesign.co and https://color-bar.com and both have the identical issue after running Google's Lighthouse from within Chrome's Element Inspector

**Comment by westonruter** [comment]
Please see https://github.com/GoogleChromeLabs/pwa-wp/issues/304
