### ISSUE TITLE
Facilitate notifying user of updated service worker

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#35]
An updated service worker defers activating until all existing client windows have gone away (e.g. via reloading browser). There should perhaps be a way to notify the user that updates are available without requiring them to have DevTools open. Such an update prompt is common on web apps, and having a standardized notice in WordPress would probably be a good idea.

In the admin the notice could be shown as an admin notice. On the frontend maybe there is no standard way to show the notice, other than to display something in the admin bar. But this isn't shown to logged-out users.

Read more about the lifecycle at https://developers.google.com/web/fundamentals/primers/service-workers/lifecycle#waiting

**Comment by westonruter** [comment]
For example, on chromestatus.com I just saw this appear in the lower right corner of the screen:

![image](https://user-images.githubusercontent.com/134745/43295413-91c16276-90f9-11e8-9cb4-e40966a2ea4b.png)

**Comment by postphotos** [comment]
@miina, please flag @alcurrie when this is ready and she'll be making sure this gets QA'd across devices. 👍
