### ISSUE TITLE
Offline commenting can fail if the user does not provide valid fields

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#364]
The comment form has a `novalidate` attribute to force server-side validation of the fields. This is done to bypass HTML5 client-side form validation, since it used to be that the validation was not reliable across browsers. Even so, `novalidate` remains. So at the moment someone could enter a comment but then leave the Name or Email empty, and submit the comment while offline. Once the user is back online, background sync will try to submit the comment but it will be rejected by WordPress due to not having a name or email. 

So the PWA plugin should remove the `novalidate` attribute from the comment form as I suggested in TRAC-47595.

**Comment by westonruter** [comment]
This may be obsolete (or punted) if offline commenting is removed per https://github.com/GoogleChromeLabs/pwa-wp/issues/363#issuecomment-1051385128.

**Comment by westonruter** [comment]
Obsolete since offline commenting has been removed in #728.

**Comment by pooja-muchandikar** [comment]
As per https://github.com/GoogleChromeLabs/pwa-wp/issues/364#issuecomment-1099827300 this feature is entirely removed from the plugin.
