### ISSUE TITLE
Deprecate integrations

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#403]
As noted in the [Service Worker wiki page](https://github.com/GoogleChromeLabs/pwa-wp/wiki/Service-Worker) section on [Integrations](https://github.com/GoogleChromeLabs/pwa-wp/wiki/Service-Worker#integrations):

> For these reasons, precaching resources should be done very sparingly. (The only two resources which are always precached are the offline page and the error page.) Instead, runtime caching should be used with a network-first caching strategy so that the latest version of a resource will be used whenever it is changed and then fallback to a previously-cached resource.

The integrations were largely experimental and in practice they've not been used 20% (as they are only usable via code opt-in) to warrant being part of the plugin itself for core merge.

**Comment by thelovekesh** [comment]
@westonruter Can you please share how we are planning to deprecate the integrations? Are we completely removing them in this version or just adding a deprecating notice for now.

If we are just going to add a message then this is just a matter of adding `_deprecated_function` in the `pwa.php`.
```php
/**
 * Load service worker integrations.
 *
 * @since 0.2.0
 * @deprecated 0.7 Support for Integrations will be removed in a future version.
 * @codeCoverageIgnore
 *
 * @param WP_Service_Worker_Scripts $scripts Instance to register service worker behavior with.
 */
function pwa_load_service_worker_integrations( WP_Service_Worker_Scripts $scripts ) {

	_deprecated_function( __FUNCTION__, '0.7', );

	if ( ! current_theme_supports( 'service_worker' ) ) {
		return;
	}

	/** WordPress Service Worker Integration Functions */
	require_once PWA_PLUGIN_DIR . '/integrations/functions.php';

	pwa_register_service_worker_integrations( $scripts );
}
```

If you have some different ideas with integrations deprecation then please let me know.

**Comment by thelovekesh** [comment]
@westonruter Any update on this one?

**Comment by westonruter** [comment]
Perhaps to start with we should add `@deprecated` tags to the classes/functions, and then when an integration is used it can emit a `console.warn()` saying something like:

```js
console.warn( "The X integration in the PWA plugin is deprecated and no longer being considered for WordPress core inclusion." );
```

That would probably be a good first step as a soft-deprecation.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

To cross check this issue added a line of code in theme's function.php file `add_theme_support( 'service_worker', true );` once this was added console error gave all deprecated errors as expected.

<img width="1280" alt="Screenshot 2022-04-20 at 5 38 08 PM" src="https://user-images.githubusercontent.com/41000648/164227078-7c760c19-63f5-4b2c-ad6e-df6d22ba053c.png">
