### ISSUE TITLE
No build "Exit status 3"

### ISSUE THREAD

**Issue by astroVibes** [xwp/pwa-wp#429]
hi everyone, I was trying this plugin, once installed I was asked to rename the folder to "pwa" and it was done, I ran the commands and they all went well (composer install and npm install) when I launched the npm run build command errors appeared,

```
> pwa-wp@ build C:\laragon\www\sitename\wp-content\plugins\pwa
> grunt build; grunt create-build-zip

Warning: Task "build;" not found. Use --force to continue.

Aborted due to warnings.
npm ERR! code ELIFECYCLE
npm ERR! errno 3
npm ERR! pwa-wp@ build: `grunt build; grunt create-build-zip`
npm ERR! Exit status 3
npm ERR!
npm ERR! Failed at the pwa-wp@ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

[2021-02-21T20_51_39_643Z-debug.log](https://github.com/GoogleChromeLabs/pwa-wp/files/6018479/2021-02-21T20_51_39_643Z-debug.log)

**Comment by westonruter** [comment]
Your terminal seems to be including `;` in the command name for some reason. Try running just `grunt build` by itself. In any case, you can just install the build from the WordPress.org directory directly instead of building it yourself.
