### ISSUE TITLE
Eliminate custom skipWaiting message in favor of de facto Workbox message

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#444]
We currently allow a client to post a `{action:'skipWaiting'}` message to cause the service worker to skip waiting (which is done by default in the SW now anyway):

https://github.com/GoogleChromeLabs/pwa-wp/blob/877ff1ee4d4a5e99c9f737383f58ee2537b5ea64/wp-includes/js/service-worker.js#L13-L22

However, Workbox indicates there is a _de facto_ message `{type:'SKIP_WAITING'}`. See https://github.com/GoogleChrome/workbox/issues/2394.

The code to handle this message is not part of a Workbox package but rather is part of the SW template: https://github.com/GoogleChrome/workbox/blob/ae29e1748bb976351db8e0c64a9ea9fc8ba2583f/packages/workbox-build/src/templates/sw-template.js#L34-L38

So we'll need to incorporate that instead of what we have now. 

This is part of the Workbox v6 upgrade and it coincides with opening up the use of `workbox.window` in #204, as the client could then do `workbox.messageSkipWaiting()`. See [v6 release notes](https://github.com/GoogleChrome/workbox/releases/tag/v6.0.0#:~:text=messageSkipWaiting).

**Comment by thelovekesh** [comment]
Changes for this issue are working as expected. I tested it by passing `{type:'SKIP_WAITING'}` using the `messageSkipWaiting` function.

I replaced SW registration script with this script in `service-workers.php`
```html
<script type="module">
	import { Workbox } from <?php echo wp_json_encode( $workbox_window_src ); ?>;

	if ( 'serviceWorker' in navigator ) {
		window.wp = window.wp || {};
		window.wp.serviceWorkerWindow = new Workbox(
			<?php echo wp_json_encode( $sw_src ); ?>,
			<?php echo wp_json_encode( $register_options ); ?>
		);


		let registration;

		const showSkipWaitingPrompt = async (event) => {
			window.wp.serviceWorkerWindow.addEventListener('controlling', () => {
				window.location.reload();
			});

			const updateAccepted = await promptForUpdate();

			if (updateAccepted) {
				window.wp.serviceWorkerWindow.messageSkipWaiting();
			}
		};

		window.wp.serviceWorkerWindow.addEventListener('waiting', (event) => {
			showSkipWaitingPrompt(event);
		});


		window.wp.serviceWorkerWindow.register();
	}

	const promptForUpdate = async () => {
		const updateAccepted = await window.confirm(
			<?php echo wp_json_encode( __( 'New content is available. Do you want to update?', 'pwa' ) ); ?>
		);

		return updateAccepted;
	};
</script>
```
and disabled `skipWaiting` by default using this filter
```php
add_filter(
	'wp_service_worker_skip_waiting', 
	__return_false()
);
```

So whenever the content of the service worker gets changed it asks to `skipWaiting` and work as expected with de facto Workbox message.

https://user-images.githubusercontent.com/54371619/164447377-2d855737-bea0-4673-9a82-796a3b971433.mp4


cc: @westonruter
