### ISSUE TITLE
Manifest doesn't have a maskable icon

### ISSUE THREAD

**Issue by teckgeekz** [xwp/pwa-wp#450]
Wordpress plugin passes all PWA checklist however fails on one single element. 
As per the New Update by Google OWA checklist there should be a Maskable Icon present.
Please fix it for the wordpress plugin.

Thank you
Error screenshot : https://prnt.sc/10r27h2

Documentation: https://web.dev/maskable-icon-audit/

**Comment by westonruter** [comment]
Please see https://github.com/GoogleChromeLabs/pwa-wp/issues/304
