### ISSUE TITLE
Offline commenting returns 405 Not Allowed or No Internet

### ISSUE THREAD

**Issue by Youdaman** [xwp/pwa-wp#456]
Hi, I'm trying to get my head around how Offline Commenting works so that I can create my own background sync script for another form. However when I try to demonstrate Offline Commenting I either get 405 Not Allowed (when I turn off my localhost server) or No Internet (when trying on a live server using airplane mode on my phone).

Is this working or still experimental?

**Comment by westonruter** [comment]
I just tested and I'm not seeing that issue, but there are problems with offline commenting. Namely it doesn't work reliably for authenticated users: #363. Perhaps that is what you're seeing?

**Comment by Youdaman** [comment]
Thanks, it could be something else then.

That said, could you please point me to an example of setting up a basic background sync, either via the PHP side of things or the JS using your version of Workbox? I've tried to copy over an existing working service worker from a Vue app but there seems to be differences, e.g. this code
```
const bgSyncPlugin = new workbox.backgroundSync.Plugin('myQueueName', {
  maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
});
```
Should work except it doesn't, and even switching out `workbox` with `wp.serviceWorker` (going by the code in wp-content\plugins\pwa\wp-includes\js\service-worker.js) it complains that `Uncaught TypeError: wp.serviceWorker.backgroundSync.Plugin is not a constructor`. Tried it without the `new` and still no luck. I'm clutching at straws here so basic examples of a bg sync with a POST would be appreciated.

**Comment by westonruter** [comment]
Sorry for the delay. I'll have time to follow up by Friday.

**Comment by westonruter** [comment]
OK, here's some code that works for me, implementing the [Basic Usage](https://developers.google.com/web/tools/workbox/modules/workbox-background-sync#basic_usage) from the Workbox docs:

```php
namespace Try_Background_Sync;

use WP_Service_Worker_Scripts;

function register_script() {
	ob_start();
	?>
	<script>
		const bgSyncPlugin = new workbox.backgroundSync.BackgroundSyncPlugin( 'myQueueName', {
			maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
		});
		workbox.routing.registerRoute(
			/\/api\/.*\/*.json/,
			new workbox.strategies.NetworkOnly({
				plugins: [
					bgSyncPlugin
				]
			}),
			'POST'
		);
	</script>
	<?php
	return str_replace( [ '<script>', '</script>' ], '', ob_get_clean() );
}

add_action(
	'wp_front_service_worker',
	function ( WP_Service_Worker_Scripts $scripts ) {
		$scripts->register( 'try-background-sync', __NAMESPACE__ . '\register_script' );
	}
);
```

I'm using `script` tags here with output buffering to just keep everything in one file. Better to have that JS code in a separate file that you pull in via `file_get_contents()`.
