### ISSUE TITLE
How to use the plugin

### ISSUE THREAD

**Issue by Benjazper** [xwp/pwa-wp#459]
Hi, I just installed the plugin but there is no settings there. So what do I need to do for the plugin to work?

**Comment by westonruter** [comment]
Please see the FAQ: https://github.com/GoogleChromeLabs/pwa-wp/wiki/FAQ#where-are-the-plugin-settings

**Comment by Benjazper** [comment]
Yes, I've seen this link multiple times but I still don't understand what to do. Do i add those codes to my site?.

**Comment by Benjazper** [comment]
Do I add the code below to my function.php and that's all? 

`add_filter( 'web_app_manifest', function( $manifest ) {
    $manifest['short_name'] = 'Shortness';
    return $manifest;
} );`

**Comment by westonruter** [comment]
You don't need to add any code. You can enable offline browsing in Reading settings.

**Comment by Benjazper** [comment]
So all I have to do is install and activated the plugin that is all. Right?

**Comment by westonruter** [comment]
Yes, and turn on the offline browsing setting if you want that.
