### ISSUE TITLE
Handle when default offline page is in a menu

### ISSUE THREAD

**Issue by hellofromtonya** [xwp/pwa-wp#46]
*The Problem* :   The default offline page should not be in a menu.  But it is possible that when selecting an existing page as the default offline page, that existing page might be included as a menu item or parent menu item within one or more existing menus.

For example:

![pwa-existing-page-in-nav](https://user-images.githubusercontent.com/7284611/42894263-045e5c5a-8a7c-11e8-97b2-6a0160be83ec.png)

Currently, no error messaging appears.

In this issue, we are exploring how best to handle this edge case.  The [discussion began here](https://github.com/xwp/pwa-wp/issues/23#issuecomment-405996763) in #23.

We need to determine whether to:

- [ ] Prevent it from happening by disallowing an existing page to be selected as the default offline page.
- [ ] Alert - notify the admin and direct him/her to each of the menus in `Appearance > Menus`
- [ ] Automatically resolve and Alert for action when needed (e.g. when the page is a parent menu item).

**Comment by hellofromtonya** [comment]
@postphotos and @jwold We need to have a discussion on the user's experience for the given scenario in this ticket.

**Comment by westonruter** [comment]
I don't know if this is something that would be a problem. I mean, I can't imagine a scenario where a user creates a page, adds it to a menu, and then selects that page to be the offline page. They'd be just shooting themselves in the foot or intentionally doing something bad. A user can do other bad things with the static homepage and posts page, and WordPress doesn't stop them from doing them (yet). So I don't think we need to worry about users doing this.

**Comment by westonruter** [comment]
Closing due to #52.
