### ISSUE TITLE
a lot of 404 errors

### ISSUE THREAD

**Issue by oecin** [xwp/pwa-wp#465]
i do not use this plugin. 
but i see a lot of 404 errors
here is the list
/wp-content/plugins/pwa/wp-includes/js/workbox-v5.1.2/workbox-background-sync.prod.js 
/wp-content/plugins/pwa/wp-includes/js/workbox-v5.1.2/workbox-core.prod.js 
/wp-content/plugins/pwa/wp-includes/js/workbox-v5.1.2/workbox-navigation-preload.prod.js 
/wp-content/plugins/pwa/wp-includes/js/workbox-v5.1.2/workbox-precaching.prod.js 
/wp-content/plugins/pwa/wp-includes/js/workbox-v5.1.2/workbox-routing.prod.js 
/wp-content/plugins/pwa/wp-includes/js/workbox-v5.1.2/workbox-strategies.prod.js

how to fix it

**Comment by westonruter** [comment]
You don't use it? Do you mean you had it active but since then you deactivated?

**Comment by oecin** [comment]
Yes,404 errors still show

**Comment by westonruter** [comment]
When you deactivate the plugin, the service worker it installed remains for the next 24 hours. That's how service workers work. After 24 hours, the browser will re-check to see if the service worker script is still there, and if not, it should uninstall it. So you should see tomorrow that these 404s no longer show up in the network console.

**Comment by oecin** [comment]
i deactivate   nearly half year........a lot of days

i do not know why still show this

**Comment by westonruter** [comment]
Share the URL to your site where the issue can be seen.
