### ISSUE TITLE
Idea: Add support for custom theme template file to be used for offline page

### ISSUE THREAD

**Issue by roborourke** [xwp/pwa-wp#50]
Although you can use a regular page as the offline page and choose a page template it might be desirable to let theme authors create a template file specifically for offline use as it could be quite different, eg. with no menus etc.

There are a couple of suitable options for this:

- `503.php` - service unavailable, also send the same status code? Not sure this is technically accurate to use, as it could be either the site or user who is offline
- `offline.php` - not status code specific and self explanatory

**Comment by westonruter** [comment]
There was some discussion about this in https://github.com/xwp/pwa-wp/issues/9#issuecomment-403262531

However, the previous discussion was about using a custom template _instead of_ having a page designated as the offline page. What I think you are suggesting is actually extending the template hierarchy to be able to select an `offline.php` for the offline page request (if a custom page template isn't already selected). I think that makes sense.

> Not sure this is technically accurate to use, as it could be either the site or user who is offline

That's a good point, and it's related to https://github.com/xwp/pwa-wp/issues/23#issuecomment-404276424.

I don't think we'd want to provide a UI to select a page both for when the client is offline _and_ when the server is offline, but if there were two separate template files which are served in these two different scenarios than this would be a way to easily show a different message based on why the page is not accessible, without requiring that the offline page be communicating with the service worker to determine the cause of the error.

Note that this would require that precaching in #48 to request two separate URLs to cache, one URL for the page template used for offline and another for the 503 response. Perhaps a query var could be used to specify which template should be used when requesting the offline page. Nevertheless, if you select a custom page template should this not override the page template hierarchy? What if you want to select the page template for the offline case, but not for the 503 case?

**Comment by nico-martin** [comment]
I think that would be a great compromise. We could add an offline.php detection. If the theme has an offline.php, the user should not be able to select an offline page. So the select box could be disabled an there could be a short text that explains that the offline.php will be used instead.

And since this is optional we can expect from the theme author to add the assets from the offline.php to the SW through the API.

**Comment by westonruter** [comment]
I wasn't thinking this specifically. Rather, that the `offline.php` template would be included with whatever the selected offline page as the queried object. But if they didn't select an offline page, then the `offline.php` template could be included and `have_posts()` would be `false`. Otherwise, if they did select an offline page then `have_post()` would be `true`.

**Comment by roborourke** [comment]
> if they didn't select an offline page, then the offline.php template could be included and have_posts() would be false. Otherwise, if they did select an offline page then have_post() would be true.

This makes sense to me, and sorry I missed the earlier discussion about it too - forgot to look through closed issues!

**Comment by westonruter** [comment]
As noted in #52 the direction now is to not have a user-specified offline page but rather to only use a static `offline.php` (and `500.php`) template (similar to how `404.php` is used). When not present in the theme, they would be pulled from `wp-includes/theme-compat` similar to how the `embed` template is handled. So importantly, the offline/500 error template hierarchy would not ever fall back to `index.php` in the theme.

So in this case, what I said in https://github.com/xwp/pwa-wp/issues/50#issuecomment-411957248 is not relevant anymore, as there would be no queried object for the error template, unless a plugin introduces the ability for the user to select a page to serve offline.

**Comment by roborourke** [comment]
Thanks for the update @westonruter, this sounds perfectly logical to me.
