### ISSUE TITLE
Serve static offline/500 template as opposed to using specially-designated page

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#52]
We had quite a bit of back-and-forth in #9 about whether to serve a static `offline.php` template or a serve a designated offline page, but went ahead with going down the route of the latter: letting the user to select the offline page. We merged the ability to select the offline page (#23 and #45) and to be able to serve this page when offline (#48).

Nevertheless, through the implementation of this ability we've discovered some problems:

* The `page.php` template could be including assets that would not be precached, and would thus be broken.
* A user could supply content (e.g. a video) that would not be precached, and thus be broken.
* Reliably precaching the header image which would be served on the offline page can be a challenge, especially if the random header option is selected.
* The designated offline page could be an existing page, and in that case should it be removed from nav menus (#46)? Should the selected offline page be excluded from search results and being added to nav menus in the first place? What if they want to use the contact page as the offline page?

These complications have circled things back to what @nico-martin recommended in https://github.com/xwp/pwa-wp/issues/9#issuecomment-403241008 as part of the offline page:

> I think the `offline.php` template would be the better solution than asking the user to pick an offline-page.

Basically this debate comes down to two separate precedences in core for serving a template: do we follow the precedence of the privacy page, or do we follow the precedence of the 404 template? It should be noted that while case could be made for allowing a custom page to be designated to be served on the 404 template, core does not provide that ability (though it could be provided by a plugin). So this feature plugin providing a way to select a custom offline page now seems strange in this way.

If going the static template route, we have another challenge if we want to preserve the theme's design as much as possible. If we look at an example [`404.php`](https://github.com/WordPress/wordpress-develop/blob/4.9.8/src/wp-content/themes/twentyseventeen/404.php) template, we can see it is not as simple as just:

```php
<?php get_header(); ?>
<p>Not found!</p>
<?php get_footer(); ?>
```

No, there are multiple levels of wrapper elements that are required by the theme in order to get the hard-coded “Not Found” content to be laid out and styled properly. So we wouldn't be able to introduce an `offline.php` that could be faithful to the theme's required markup structure. But even if we did, there would be a chance that content in the header or footer that would fail to precache anyway.

One of the arguments I had about going with a user-selected page is that it would allow us to fully use the template hierarchy, where a theme could still fully be served with a single `index.php`. In such a theme, the 404 case can be built in by having a standard `if ( ! have_posts() )` condition. If a user-selected page were used, then it would be included in The Loop™ like any other content, and there wouldn't be the need for an additional hard-coded condition like `elseif ( is_offline() )`.

Nevertheless, a theme that only contains an `index.php` template is not exclusively using this template on a site. Enter the [`theme-compat` directory](https://github.com/WordPress/wordpress-develop/tree/master/src/wp-includes/theme-compat), and in particular [`embed.php`](https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/theme-compat/embed.php). When calling `locate_template()` it will first check if a given template exists in the child theme and if not it checks the parent theme. If it doesn't exist in either of those locations, it then checks the `theme-compat` directory. And this is where the post embed template is served from in most WordPress themes, since `embed.php` is normally not implemented. And this is a very similar situation to where themes will be once an offline page is introduced.

So the best solution for proposed core merge is to design a good-looking generic `offline.php` (and `500.php`) be located in the `theme-compat` directory to be served when the user/site is offline. If a theme defines a `offline.php` then they will have to do additional work to make sure that any assets used on this page are included among those that are precached. Additionally, **a plugin should be able to override which URL is used for the offline page so that they can provide the ability to select a custom page**.

So in the end a theme would not have to define an `offline.php` to see the site-specific offline page, but they should define one if they want to have the offline page styled according to their theme, instead of a generic one.

**Comment by amedina** [comment]
This is right on target.

**Comment by westonruter** [comment]
As alluded to above, in the case of a 500 Internal Server Error, we can show a template separate from the `offline.php`. This was raised by @roborourke in #50. This will replace the white screen of death with a site-specific message.

When PHP is actually outputting an error message as part of the 500 error we could display this inside of a `details` element, which is closed by default. This will ensure that the underlying error message is not hidden, and this template could potentially be used to contact the webmaster to alert them of the problem. Technically, if we don't want to inject the error message HTML straight into the DOM, the error message could be injected into an `iframe` via the `srcdoc` attribute.
