### ISSUE TITLE
PHP Notice:  is_offline was called incorrectly

### ISSUE THREAD

**Issue by Youdaman** [xwp/pwa-wp#538]
Couple of intermittent errors/notices in debug.log:

> PHP Notice:  is_offline was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. 

> PHP Notice:  is_500 was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. 

Line 98 of wp-content\plugins\pwa\wp-includes\general-template.php seems to be the problem?

```php
/**
 * Add no-robots meta tag to error template.
 *
 * @todo Is this right? Should we add_action when we find out that the filter is present?
 * @see wp_no_robots()
 * @since 0.2
 */
function wp_add_error_template_no_robots() {
	if ( is_offline() || is_500() ) {
		wp_no_robots();
	}
}
```

**Comment by westonruter** [comment]
The `wp_add_error_template_no_robots()` function runs at `wp_head` and `error_head`:

https://github.com/GoogleChromeLabs/pwa-wp/blob/a9213f04fe1dce8ecb787cf7a08d6e27686ce914/wp-includes/default-filters.php#L20-L21

Perhaps you have a template that is calling `wp_head()` unexpectedly?

**Comment by westonruter** [comment]
@Youdaman Sorry for the delay on this. Another user reported the same issue in the support forums. I was able to reproduce the issue and I've submitted a fix: #712. Could you see if that fixes the issue for you if you're still using the plugin?

**Comment by pooja-muchandikar** [comment]
Hi @westonruter,

Me and @thelovekesh tried to reproduce the issue but we were not able to reproduce it. Can you please help us to QA this issue?

cc: @maitreyie-chavan

**Comment by westonruter** [comment]
✅ **QA Passed**

This is how I could reproduce the issue by putting the following in a plugin:

```php
add_action( 'plugin_loaded', function () {
	$query = new WP_Query();
	$query->parse_query( 's=test' );
} );
```

Before the change I would get errors like:

<blockquote><b>Notice</b>:  is_offline was called <strong>incorrectly</strong>. Conditional query tags do not work before the query is run. Before then, they always return false. Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 3.1.0.) in <b>/app/public/core-dev/src/wp-includes/functions.php</b> on line <b>5775</b></blockquote>

After the change, the notices go away.
