### ISSUE TITLE
Allow for Workbox.js scripts to be loaded from CDN

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#543]
As requested on a [support forum topic](https://wordpress.org/support/topic/please-help-needed-on-js/), some sites may want to load the Workbox scripts from a CDN instead of loading them from origin.

This is not currently supported, as seen here:

https://github.com/GoogleChromeLabs/pwa-wp/blob/f9fc1cbd2140d5874064c43767d5382faa3e22cb/wp-includes/components/class-wp-service-worker-configuration-component.php#L55-L79

Perhaps this could be supported by allowing `$options` to be filtered in PHP.

**Comment by westonruter** [comment]
Eventually this could be achieved by passing the paths through the `includes_url()` function so that it could be filtered.

**Comment by westonruter** [comment]
For now, we can just make use of the `plugins_url()` function so that the `plugins_url` filter is applied to the Workbox URLs

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

To cross check this issue registered a new plugin and was able to load the Workbox.js scripts through CDN, as per the URL passed in the code.

<img width="505" alt="Screenshot 2022-04-20 at 6 03 05 PM" src="https://user-images.githubusercontent.com/41000648/164231117-fda2fa8f-dca8-419b-9519-ddc1cacf3841.png">

---

<img width="989" alt="Screenshot 2022-04-20 at 5 56 15 PM" src="https://user-images.githubusercontent.com/41000648/164231488-4620dd34-fe37-444d-9908-8dfa4a3634b0.png">
