### ISSUE TITLE
Make apple-touch-startup-image link tags filterable

### ISSUE THREAD

**Issue by jefferyto** [xwp/pwa-wp#586]
Not sure if there is interest in merging a PR for this, so I decided to open an issue first.

Apparently, the splash image for iOS needs to be sized exactly to the screen to be displayed. The [official documentation](https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html#//apple_ref/doc/uid/TP40002051-CH3-SW6) doesn't mention this, but there are lots of articles/blog posts (like [this one](https://medium.com/appscope/adding-custom-ios-splash-screens-to-your-progressive-web-app-41a9b18bdca3) and [this one](https://www.simicart.com/blog/pwa-splash-screen/#For_iOS)) that do cover this constraint.

This leads to a [horrible mess of link tags](https://gist.github.com/EvanBacon/7fd4dc3be3d00096579bb0b134c56ec7) to match every possible Apple device and [entire](https://github.com/onderceylan/pwa-asset-generator) [projects](https://appsco.pe/developer/splash-screens) dedicated to generating these images.

Instead of managing this here, I suggest adding a filter (maybe `apple_touch_startup_image`) that plugins/themes can use to add all the splash screens they want.

**Comment by jefferyto** [comment]
Incidentally, because the manifest icons are sorted in [ascending order](https://github.com/GoogleChromeLabs/pwa-wp/blob/4aa2b8a791afd746cc8a02f5df9f896cb52c0f34/wp-includes/class-wp-web-app-manifest.php#L363) and the [first icon](https://github.com/GoogleChromeLabs/pwa-wp/blob/4aa2b8a791afd746cc8a02f5df9f896cb52c0f34/wp-includes/class-wp-web-app-manifest.php#L89) in the sorted list is used, this means the smallest icon is used for the current apple-touch-startup-image link tag. Not sure if this was intentional.

**Comment by westonruter** [comment]
A filter seems like a good way to mitigate this issue. 

I expect (hope) that this will become irrelevant once Safari (please) implements support for Web App Manifests.

> the smallest icon is used for the current apple-touch-startup-image link tag. Not sure if this was intentional.

This was not intentional, AFAIK. Making the app installable on iOS was implemented in https://github.com/GoogleChromeLabs/pwa-wp/issues/118 via https://github.com/GoogleChromeLabs/pwa-wp/pull/129.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

To cross check this issue registered a new plugin and was able print apple touch startup image link tags

<img width="961" alt="Screenshot 2022-04-20 at 7 09 30 PM" src="https://user-images.githubusercontent.com/41000648/164243364-c7a45c18-2b40-4b1e-8325-56d9883bac47.png">

---

![image](https://user-images.githubusercontent.com/41000648/164243464-82f12f2d-911b-4547-89f5-f618da727a04.png)

**Comment by halilesen** [comment]
> QA Passed ✅
> 
> To cross check this issue registered a new plugin and was able print apple touch startup image link tags
> 
> <img alt="Screenshot 2022-04-20 at 7 09 30 PM" width="961" src="https://user-images.githubusercontent.com/41000648/164243364-c7a45c18-2b40-4b1e-8325-56d9883bac47.png">
> 
> ![image](https://user-images.githubusercontent.com/41000648/164243464-82f12f2d-911b-4547-89f5-f618da727a04.png)

This didn't work for me. I also mentioned this on the support forum. [Here.](https://wordpress.org/support/topic/apple-startup-image/) I am using the latest iOS version. What am I missing?
