### ISSUE TITLE
Manifest or service worker undetected

### ISSUE THREAD

**Issue by aurelienpierre** [xwp/pwa-wp#619]
I'm using PWA on WP with Avada theme (which has configuration fields for PWA) plus some personal code for extra features, on https://photo.aurelienpierre.com.

On Google Chrome/Chromium, the service worker is properly detected but the manifest is not. Yet, https://photo.aurelienpierre.com/wp-json/wp/v2/web-app-manifest works. Notice I also use WP Rocket (caching plugin) which tries to cache and gzip this file, so I explicitly removed it from the cache. The service worker is properly detected.

On Mozilla Firefox desktop, the manifest is detected but the service worker is not. When I'm logged in as admin, the console says:
```
Uncaught (in promise) TypeError: ServiceWorker script at https://photo.aurelienpierre.com/wp.serviceworker?lang=en for scope https://photo.aurelienpierre.com/?lang=en encountered an error during installation.
Uncaught (in promise) TypeError: ServiceWorker script at https://photo.aurelienpierre.com/wp-admin/admin-ajax.php?action=wp_service_worker for scope https://photo.aurelienpierre.com/wp-admin/ encountered an error during installation.
```
If I use anonymous browsing, it says nothing, but no service worker is started.

Interestingly, Mozilla Firefox Mobile is the only browser that lets me install the PWA. 

```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_DISPLAY', true );
define( 'WP_SERVICE_WORKER_DEBUG_LOG', true );
```
returns nothing related to PWA/service workers.

I'm lost.

Additional context : I'm using multisite install with subdomain, but PWA is enabled and configured only for one of them.

**Comment by westonruter** [comment]
Your manifest is getting parsed as being in the `body` and that is why it is not being detected:

![image](https://user-images.githubusercontent.com/134745/135306720-f85af80d-0432-4db4-a3f5-1a60e238db56.png)

This is due to the `<div id="overlay-loader" style="display: none">` element you have in your `head`, which is not valid HTML.

A similar issue was reported before on the support forums: https://wordpress.org/support/topic/errors-loading-manifest/

Firefox reads the `link[rel=manifest]` from the `body` whereas Chromium does not, so that's why it works in Firefox.

**Comment by aurelienpierre** [comment]
Thanks a lot ! So, problem solved for Chrom(e|ium). 

Now, for Firefox desktop, the service worker is still broken. Any pointer ?

**Comment by westonruter** [comment]
I'm seeing the service worker running in Firefox:

![image](https://user-images.githubusercontent.com/134745/135362275-83b150e2-653f-43b0-8df8-7292f28800f5.png)

**Comment by aurelienpierre** [comment]
Ok, weird that it doesn't work here. Thanks for all your help anyway ! Is there a place I can send you a beer ?

**Comment by westonruter** [comment]
No but you can leave a plugin review on WordPress.org. Thanks!
