### ISSUE TITLE
Not working with virtual localhost

### ISSUE THREAD

**Issue by CodeLearner21** [xwp/pwa-wp#644]
We are having problem to test this plugin with one of our WordPress website installed on 
custom virtual host created using WAMP server e.g. http: // localhost.myapp.com
Where as it is working fine with project as sub directory within localhost root folder e.g. http: // localhost:8080/myapp

**Comment by westonruter** [comment]
Service workers require HTTPS to be installed _unless_ the hostname is `localhost`. See https://developers.google.com/web/fundamentals/primers/service-workers#you_need_https
