### ISSUE TITLE
Navigation preload is causing every navigation request to be doubled

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#67]
When browsing the WP Admin, I found that links for action links with nonces that trash/restore posts could fail with messages saying that the post was already trashed or restored. Similarly, I found that when I had a “flash” message in a transient that was deleted as soon as it was accessed, that this message would never show up. 

The reason for these issues is that every page navigation in the admin is currently causing two requests to be made, one with `Service-Worker-Navigation-Preload` request header, and another without. This is very problematic for the admin when clicking action links like restore/trash because they are not idempotent. That is why trashing was failing because the browser was showing you the response to the second request, when the item was already trashed.

![image](https://user-images.githubusercontent.com/134745/45385145-e0879700-b5c4-11e8-8f33-3f3f919ecf3b.png)

We need to figure out a solution to this.

**Comment by westonruter** [comment]
What seems to be needed is a way to turn off navigation preload when the service worker is up and running. But I don't think that is currently possible.

**Comment by westonruter** [comment]
Otherwise, the only alternative I can see at present is to turn off navigation preload. That is not ideal either because it can mean increased latency. But this is better than the user getting a broken experience. In particular, WordPress often generates nonce action URLs like:

```
https://src.wordpress-develop.test/wp-admin/post.php?post=2908&action=trash&_wpnonce=b1eff11df2
```

These are in reality alternatives to `POST` requests. They're `GET` requests that aren't idempotent. It's not great that WordPress does this commonly, but it's the way things are. There's a dedicated function for it ([`wp_nonce_url()`](https://developer.wordpress.org/reference/functions/wp_nonce_url/)). When clicking Trash and the preload request is made while the service worker also makes a request, and if the preload request is handled by WordPress first then the subsequent request from the service worker is going to rejected from WordPress because the post has already been trashed. The result is:

> ![image](https://user-images.githubusercontent.com/134745/45714185-cd854180-bb45-11e8-9be5-d588fdba09ce.png)

If navigation preload is enabled it seems that every navigation is currently resulting in two HTTP requests being made to the URL being navigated to. This seems problematic beyond the non-idempotent links. It could also adversely affect server logs and analytics.

**Comment by westonruter** [comment]
Another workaround could potentially be to hook into WordPress early to detect any request with a `Service-Worker-Navigation-Preload` header, and then short-circuit if there is also an `action` and `_nonce` query param. This doesn't seem like an ideal solution since there are still two HTTP requests being made for each navigation.

**Comment by westonruter** [comment]
Another example, when the 500 error template is involved:

![image](https://user-images.githubusercontent.com/134745/45720691-06c7ac80-bb5a-11e8-839c-6073f86c7727.png)

**Comment by westonruter** [comment]
Another idea would be to enable navigation preload when the service worker goes to sleep, and then turn it back on once it wakes up. (h/t @amedina) This would depend on there being a reliable way to detect when the service worker becomes active (to disable preload) and when it gets terminated (to re-enable preload).

Workbox doesn't yet have a way yet to disable navigation preload. See https://github.com/GoogleChrome/workbox/issues/1648.

**Comment by igrigorik** [comment]
Could we just make a dependency on 3.6.0? Looks like @jeffposnick already landed a patch for this. :)

**Comment by amedina** [comment]
Yep; we filed a feature request and it was done quickly by Jeff. Good
support 😊

**Comment by westonruter** [comment]
Opened PR to update Workbox to 3.6.1: https://github.com/xwp/pwa-wp/pull/77

This won't fix the issue in itself.

Another alternative we discussed over chat is to await the `preloadResponse` before proceeding to `fetch` in the service worker, as [per MDN](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/navigationPreload#Example):

```js
addEventListener('fetch', event => {
  event.respondWith(async function() {
    // Respond from the cache if we can
    const cachedResponse = await caches.match(event.request);
    if (cachedResponse) return cachedResponse;

    // Else, use the preloaded response, if it's there
    const response = await event.preloadResponse;
    if (response) return response;

    // Else try the network.
    return fetch(event.request);
  }());
});
```

That should actually be what was missing in the first place.
