### ISSUE TITLE
Error template placeholder HTML comments can be stripped out by minifiers

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#709]
As mentioned by @stack-exchange in a [gist comment](https://gist.github.com/westonruter/900611f075374c5468ea492f23ad4810?permalink_comment_id=4071849#gistcomment-4071849):

> Placeholder comment inserted by `wp_service_worker_error_message_placeholder()` get stripped by AMP plugin.

The issue is the AMP Optimizer's `MinifyHtml` transformer which strips out HTML comments. This will also be an issue with other optimization plugins. Therefore, instead of `wp_service_worker_error_message_placeholder()` and `wp_service_worker_error_details_template()` outputting HTML comments, they should instead output HTML elements, identified by an ID.

https://github.com/GoogleChromeLabs/pwa-wp/blob/a1f9125bca4c61aa95316a1bd725386175301d4e/wp-includes/template.php#L168-L173

https://github.com/GoogleChromeLabs/pwa-wp/blob/a1f9125bca4c61aa95316a1bd725386175301d4e/wp-includes/template.php#L154-L166

Note this will make the regex a bit more complicated here:

https://github.com/GoogleChromeLabs/pwa-wp/blob/d415cb264bd39a0aabb7da0b5a9f40727161662c/wp-includes/js/service-worker-navigation-routing.js#L75

**Comment by thelovekesh** [comment]
@westonruter I was working upon this and tried the following idea:
For error message
```php
function wp_service_worker_error_message_placeholder() {
	// echo '<p><!--WP_SERVICE_WORKER_ERROR_MESSAGE--></p>';
	echo '<p><span id="wp-service-worker-error-message"></span></p>';
}
```
and replace whole span element with following reges
```js
/[<]span id="wp-service-worker-error-message">(\s)*[<]\/span>/
```

For error message details:
```php
function wp_service_worker_error_details_template( $output = '' ) {
	if ( empty( $output ) ) {
		$output = '<details id="error-details"><summary>' . esc_html__( 'More Details', 'pwa' ) . '</summary>{{{error_details_iframe}}}</details>'; // phpcs:ignore WordPressVIPMinimum.Security.Mustache.OutputNotation -- Variable includes iframe tag.
	}
	// echo '<!--WP_SERVICE_WORKER_ERROR_TEMPLATE_BEGIN-->';
	echo '<span id="wp-service-worker-error-template-begin"></span>';
	echo wp_kses_post( $output );
	// echo '<!--WP_SERVICE_WORKER_ERROR_TEMPLATE_END-->';
	echo '<span id="wp-service-worker-error-template-end"></span>';
}
```
and replace whole span element with following reges
```js
/([<]span id="wp-service-worker-error-template-begin">(\s)*[<]\/span>)((?:.|\n)+?)([<]span id="wp-service-worker-error-template-end">(\s)*[<]\/span>)/
```

If you some another ideas please share and let me know your thoughts on the above method if it can work in our current scenerio.

**Comment by westonruter** [comment]
I just realized that we're using Mustache-like tokens in `wp_service_worker_error_details_template()` already (e.g. `{{{error_details_iframe}}}`). So what if we actually use Mustache tokens instead of HTML comments and instead of “milestone” HTML tags?

So that could be:

```php
function wp_service_worker_error_message_placeholder() {
	echo '<p>{{{WP_SERVICE_WORKER_ERROR_MESSAGE}}}</p>';
}
```

And:

```php
function wp_service_worker_error_details_template( $output = '' ) {
	if ( empty( $output ) ) {
		$output = '<details id="error-details"><summary>' . esc_html__( 'More Details', 'pwa' ) . '</summary>{{{error_details_iframe}}}</details>'; // phpcs:ignore WordPressVIPMinimum.Security.Mustache.OutputNotation -- Variable includes iframe tag.
	}
	echo '{{{WP_SERVICE_WORKER_ERROR_TEMPLATE_BEGIN}}}';
	echo wp_kses_post( $output );
	echo '{{{WP_SERVICE_WORKER_ERROR_TEMPLATE_END}}}';
}
```

**Comment by thelovekesh** [comment]
I found moustache template tokens more suitable in our use case. So using mustache- tokens at the place of HTML tags.

**Comment by pooja-muchandikar** [comment]
QA Passed ✅ 

Offline pages are rendered with proper as expected messages

<img width="1280" alt="Screenshot 2022-04-20 at 7 10 57 PM" src="https://user-images.githubusercontent.com/41000648/164244825-da0da26a-88b0-45b0-95e3-f037553394d3.png">

---

<img width="1280" alt="Screenshot 2022-04-20 at 7 11 17 PM" src="https://user-images.githubusercontent.com/41000648/164244846-ed991be4-55ff-4af7-be88-6715deeaaf68.png">
