### ISSUE TITLE
Rely on `WP_Scripts` for all plugin functionality and introduce components

### ISSUE THREAD

**Issue by felixarntz** [xwp/pwa-wp#71]
@westonruter and I chatted for a bit about the code structure of the plugin and how to reduce complexity while making the functionality more straightforward and flexible at the same time.

Here's my suggestion as a takeaway from this discussion:
* Let's split `WP_Service_Workers` into two different classes:
    * `WP_Service_Worker_Scripts` will contain the script registry part and will extend `WP_Scripts`.
    * `WP_Service_Workers` will contain the `serve()` method and handle everything related to actually serving the service worker for frontend or admin.
* The `wp_service_worker` action should be removed. In terms of timing, it is problematic to have it run independently of the `wp_front_service_worker` / `wp_admin_service_worker` action respectively. A plugin wanting to register scripts for both scopes could simply hook the same callback into both actions.
* The instance of `WP_Service_Worker_Scripts` should be passed to the `wp_front_service_worker` / `wp_admin_service_worker` actions.
* An interface `WP_Service_Worker_Component` should be introduced. Components take care of core service worker functionality, for example outputting configuration via the base script (currently part of `WP_Service_Workers::get_base_script()`, would then move into a `WP_Service_Worker_Configuration_Component`) or outputting the script for handling precaching URLs (would move into a `WP_Service_Worker_Precaching_Routes_Component`). The interface should have a method `serve( WP_Service_Worker_Scripts $scripts )` and a method `get_priority()`. The `WP_Service_Workers` class will be aware of all available components and hook each `serve()` method into both the frontend and admin service worker actions, at the priority returned by `get_priority()`.
* An interface `WP_Service_Worker_Registry` should be introduced. This is a general interface defining a unified behavior for any registerable content. It should be implemented by `WP_Service_Worker_Scripts`, as well as all registries that belong to a specific component, for example the precache component allows other code to register precache URLs (see more below). The interface should have a method `register( $handle, $args = array() )` and a method `get_all()`.
* An interface `WP_Service_Worker_Registry_Aware` should be introduced, with a single `get_registry()` method. This should be implemented by components that allow other code to integrate with themselves. For example, `WP_Service_Worker_Precaching_Routes_Component` would implement this interface in combination with its accompanying `WP_Service_Worker_Precaching_Routes` (which implements `WP_Service_Worker_Registry`, as already hinted above).
* The `WP_Service_Worker_Scripts` class would be instantiated from the `WP_Service_Workers` class, and it would (in addition to its own methods for adding scripts) provide access to all component registries, i.e. all registries returned by the `get_registry()` method of a component (which can easily be detected via the `WP_Service_Worker_Registry_Aware` interface that they would implement. This would allow plugins and other integrations to easily register everything from a centralized point, as the `WP_Service_Worker_Scripts` instance is passed to the service worker actions. A plugin could then for example call `$scripts->precaching_routes()->register( ... )`.
* The integrations (see `WP_Service_Worker_Integration`) as they exist now would almost remain the same. The only thing they would receive in addition would be a `get_priority()` method, in order to determine the priority they are hooked into the actions. The code would also be adjusted to account for the removal of the `wp_service_worker` action (mentioned earlier).

--
These changes will introduce the following clear responsibilities:
* `WP_Service_Workers` as main entry point to the service worker functionality.
* `WP_Service_Worker_Scripts` as the main registry that plugin developers would interact with, via the `wp_front_service_worker` / `wp_admin_service_worker` actions.
* Components handle crucial core functionality for service workers. These are hard-coded and it is not possible for plugins to register additional components. Those are purely for solid code organization and to keep the `WP_Service_Workers` and `WP_Service_Worker_Scripts` clean and preserve their single responsibility. Anything that happens in a component could theoretically be added as a script directly, components just make their respective functionality much easier to use than if one had to manually register a custom script for it.
* Component registries allow to modify components that support registration of their own data.
* Integrations are an alternative object-oriented way of integrating with the plugin's service worker(s). It is simply a layer around hooking a callback into the `wp_front_service_worker` / `wp_admin_service_worker` actions directly. All default integrations (such as for the Custom Logo or Custom Header core features) should use the integration approach, while plugin developers can use whatever of the two approaches they prefer.

Let me know if you have any suggestions or concerns about this. I'll move forward with a PR for these changes tomorrow. With that in place, it might also be easier to see how all of the above comes together.

**Comment by westonruter** [comment]
Also, the scope argument for registering a script would be removed in favor of just registering scripts at `wp_front_service_worker` or `wp_admin_service_worker`. Right?

**Comment by felixarntz** [comment]
@westonruter Ah right, I forgot to include it here, but the PR does it.
