### ISSUE TITLE
GTMetrix shows slow load because of PWA (Avada+W3TotalCache+Clouflare

### ISSUE THREAD

**Issue by martini09617** [xwp/pwa-wp#724]
GTMetrix slow load because of PWA (Avada+W3TotalCache+Clouflare
See the waterfall [here](https://gtmetrix.com/reports/babybello.nl/LcdfUd2S/).

**Comment by westonruter** [comment]
Please don't open both a support forum topic _and_ a GitHub issue for the same thing. I'm closing this in favor of your [support topic](https://wordpress.org/support/topic/gt-metrix-shows-in-waterfall-long-waiting-time-by-pwa/).
