### ISSUE TITLE
Add doc related to setting up `pre-commit` hook

### ISSUE THREAD

**Issue by thelovekesh** [xwp/pwa-wp#736]
Currently, we are using `lint-staged` to run linter on staged files but we are lacking documentation to add `lint-staged` on the `pre-commit` hook.
We can add a code snippet in the wiki that can help contributors/devs to set up the `pre-commit` hook something like this:
```bash
echo "set -e; composer run-script pre-commit" > .git/hooks/pre-commit
chmod +x .git/hooks/pre-commit
```

One more thought came up to my mind. What if the user is on Windows OS?
Should we add husky to overcome this issue? We can add a `pre-commit` hook using husky on the `prepare` script. So when the user [runs](https://docs.npmjs.com/cli/v8/using-npm/scripts#life-cycle-scripts) `npm install`, husky will add a `pre-commit` hook.

**Comment by westonruter** [comment]
Using Husky would work. Or else there can just be Windows-specific instructions. 

I'm a bit wary of `npm install` having such side effects.

**Comment by thelovekesh** [comment]
> I'm a bit wary of npm install having such side effects.

`prepare` shouldn't have any side effects we need to worry about as a project like Gutenberg also uses it. Also using `husky` will make sure the `pre-commit` hook is being used properly. I think we should give it a try 👍🏼

**Comment by westonruter** [comment]
By side effects, I mean `npm install` doing anything other than populating `node_modules` and writing `package-lock.json`. But that's also what `--ignore-scripts` can avoid, so if you want to add husky I'm fine with it.
