### ISSUE TITLE
Custom Install Button

### ISSUE THREAD

**Issue by NicoHood** [xwp/pwa-wp#773]
Hi again!
I'd like to have a special page on my website where the user can click a button to install the PWA (rather than going via the browser menu).

[In the FAQ](https://github.com/GoogleChromeLabs/pwa-wp/wiki/FAQ) it says, that this is not implemented. However when I click on the more information link, it talks about providing a general website button that appears when the browser supports app installing. I guess that is already implemented in the meantime? At least google chrome asks me to install the app in a small banner at the bottom. But I might be wrong about the details, that's why I ask.

Now I got the following questions:
* How to disable that automatic footer button/banner?
* How could I manually add a custom button?

About the custom button: Maybe we could add the relevant javascript to this plugin and only make it trigger for some specialy marked buttons. Maybe with a custom id or class, that you can set in the custom block attributes, like `pwa-custom-install-button` class.

**Comment by westonruter** [comment]
Hi. The custom install button is not implemented as part of this plugin, but the link in the FAQ shows you how to implement it yourself: https://web.dev/customize-install/

**Comment by NicoHood** [comment]
And this button? Where does it come from? From chrome?

![Screenshot_2022-04-24-21-02-45-154_com android chrome](https://user-images.githubusercontent.com/6888294/165150870-8e1b2b43-041e-4149-b817-c6a73a7e6f29.jpg)

**Comment by westonruter** [comment]
Yes, it comes from Chrome. On desktop the button appears in the omnibox (location bar): https://web.dev/pwa-install-addressbar/

**Comment by NicoHood** [comment]
I just tried that, but it does not work. I am a javascript noob though. I've added it as php snippet:

```php
add_action( 'wp_head', function () { ?>
<script>
// Initialize deferredPrompt for use later to show browser install prompt.
let deferredPrompt;

window.addEventListener('beforeinstallprompt', (e) => {
  // Prevent the mini-infobar from appearing on mobile
  e.preventDefault();
  // Stash the event so it can be triggered later.
  deferredPrompt = e;
  // Update UI notify the user they can install the PWA
  showInstallPromotion();
  // Optionally, send analytics event that PWA install promo was shown.
  console.log(`'beforeinstallprompt' event was fired.`);
});

document.getElementById("pwa-install-button").addEventListener('click', async () => {
  // Hide the app provided install promotion
  hideInstallPromotion();
  // Show the install prompt
  deferredPrompt.prompt();
  // Wait for the user to respond to the prompt
  const { outcome } = await deferredPrompt.userChoice;
  // Optionally, send analytics event with outcome of user choice
  console.log(`User response to the install prompt: ${outcome}`);
  // We've used the prompt, and can't use it again, throw it away
  deferredPrompt = null;
});

</script>
<?php } );
```

Here is a test url: https://blog.nicohood.de/pwa-install-test

**Comment by westonruter** [comment]
There is an error in the console:

![image](https://user-images.githubusercontent.com/134745/165152819-18bf906a-6a84-414d-ae5e-b45407ec26b5.png)

The problem is that you're adding the event listener to the button in the `head` but that is before the button has been added to to the page.

Try using `wp_footer` instead of `wp_head` as the action.

**Comment by NicoHood** [comment]
This now works. I had to remove a lot of stuff from the example.

```php
add_action( 'wp_head', function () { ?>
<script>
// Initialize deferredPrompt for use later to show browser install prompt.
let deferredPrompt;

window.addEventListener('beforeinstallprompt', (e) => {
  // Prevent the mini-infobar from appearing on mobile
  e.preventDefault();
  // Stash the event so it can be triggered later.
  deferredPrompt = e;
  // Optionally, send analytics event that PWA install promo was shown.
  console.log(`'beforeinstallprompt' event was fired.`);
});
	
window.onload=function(){
    var buttonInstall = document.getElementById("pwa-install-button");
    buttonInstall.addEventListener("click", buttonInstallClickHandler);
}

async function buttonInstallClickHandler() {
  // Show the install prompt
  deferredPrompt.prompt();
  // Wait for the user to respond to the prompt
  const { outcome } = await deferredPrompt.userChoice;
  // Optionally, send analytics event with outcome of user choice
  console.log(`User response to the install prompt: ${outcome}`);
  // We've used the prompt, and can't use it again, throw it away
  deferredPrompt = null;
};

</script>
<?php } );
```

**Comment by NicoHood** [comment]
And this works for classes:

```php
add_action( 'wp_head', function () { ?>
<script>
// Initialize deferredPrompt for use later to show browser install prompt.
let deferredPrompt;

window.addEventListener('beforeinstallprompt', (e) => {
  // Prevent the mini-infobar from appearing on mobile
  e.preventDefault();
  // Stash the event so it can be triggered later.
  deferredPrompt = e;
  // Optionally, send analytics event that PWA install promo was shown.
  console.log(`'beforeinstallprompt' event was fired.`);
});
	
window.onload=function(){
	const installButtons = document.getElementsByClassName("pwa-install-button");
	for (buttonInstall of installButtons){
		buttonInstall.addEventListener("click", buttonInstallClickHandler);
	}
    //var buttonInstall = document.getElementById("pwa-install-button");
    //buttonInstall.addEventListener("click", buttonInstallClickHandler);
}

async function buttonInstallClickHandler() {
  // Show the install prompt
  deferredPrompt.prompt();
  // Wait for the user to respond to the prompt
  const { outcome } = await deferredPrompt.userChoice;
  // Optionally, send analytics event with outcome of user choice
  console.log(`User response to the install prompt: ${outcome}`);
  // We've used the prompt, and can't use it again, throw it away
  deferredPrompt = null;
};

</script>
<?php } );
```

Do you recommend the onload() function or the footer section? I have no idea what would be better.

**Comment by westonruter** [comment]
I don't recommend using `window.onload`. Better to use `window.addEventListener( 'load', ... )`. You could also consider `DOMContentLoaded` event on the `document`. Using that would be better because it would avoid the possibility that the user could click on the button before the window loads, ensuring that the click is not lost.

**Comment by NicoHood** [comment]
Thanks! So you say I can still keep it in the header? Or should it also move to the footer? I am also not sure if this javascript gets minified correctly. Wouldn't it make sense to integrate this into this plugin?

```php
add_action( 'wp_head', function () { ?>
<script>
// https://github.com/GoogleChromeLabs/pwa-wp/issues/773	
// https://web.dev/customize-install/

// Initialize deferredPrompt for use later to show browser install prompt.
let deferredPrompt;

window.addEventListener('beforeinstallprompt', (e) => {
  // Prevent the mini-infobar from appearing on mobile
  //e.preventDefault();
  // Stash the event so it can be triggered later.
  deferredPrompt = e;
  // Optionally, send analytics event that PWA install promo was shown.
  console.log(`'beforeinstallprompt' event was fired.`);
});
	
document.addEventListener("DOMContentLoaded", listenForInstallButtonClick);
	
function listenForInstallButtonClick() {
	const installButtons = document.getElementsByClassName("pwa-install-button");
	for (installButton of installButtons){
		installButton.addEventListener("click", installButtonClickHandler);
	}
}

async function installButtonClickHandler() {
  // Show the install prompt
  deferredPrompt.prompt();
  // Wait for the user to respond to the prompt
  const { outcome } = await deferredPrompt.userChoice;
  // Optionally, send analytics event with outcome of user choice
  console.log(`User response to the install prompt: ${outcome}`);
  // We've used the prompt, and can't use it again, throw it away
  deferredPrompt = null;
};

</script>
<?php } );
```

**Comment by westonruter** [comment]
When using `DOMContentLoaded`, you can put it in the head or the footer. It doesn't really matter, although footer would be _slightly_ better. Also, it won't be minified but it is not really necessary since it is not much JS anyway.

**Comment by rishiimmehra** [comment]
Hello @NicoHood and @westonruter this code is working perfectly but when it's sucessfully installed how should hide the install button look i onlly konw HTML CSS and tiny bit of javascript but it is not enough can you please explain it. Thanks in advance
