### ISSUE TITLE
AMP Hooks for ServiceWorker

### ISSUE THREAD

**Issue by nico-martin** [xwp/pwa-wp#84]
@westonruter I've seen you are using `wp_footer` to install the ServiceWorker on AMP (https://github.com/xwp/pwa-wp/blob/master/amp/class-amp-service-worker.php#L172)
Is there a reason you are not using `amp_post_template_footer`?

it seems like neither https://wordpress.org/plugins/accelerated-mobile-pages/ nor https://wordpress.org/plugins/amp/ support `wp_footer`.
Here's how I implemented SW for AMP: https://github.com/SayHelloGmbH/progressive-wordpress/blob/master/Classes/class-amp.php

**Comment by westonruter** [comment]
Hey! `amp_post_template_footer` is only relevant in the plugin's classic mode. You can see that it is also being used here: https://github.com/xwp/pwa-wp/blob/600240f4dc8878dc0b9b27190df0d37831d026fb/amp/class-amp-service-worker.php#L180

But going forward for the AMP plugin, where theme support is now the recommended way to implement AMP, the use of `wp_footer` will be the way to go.
