### ISSUE TITLE
Admin assets integration not respecting custom WordPress directory

### ISSUE THREAD

**Issue by felixarntz** [xwp/pwa-wp#844]
On my site where I'm using WordPress in a `wp` subdirectory (i.e. my WP Admin is not under `/wp-admin`, but rather `/wp/wp-admin`), I consistently get JS errors like when browsing my WP Admin:
```
Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":".../wp-admin/images/wheel.png","status":404}]
```

It's different WordPress core images depending which admin screen I visit, but the underlying problem is that the PWA plugin does not consider the correct admin URL. I believe this problem happens due to https://github.com/GoogleChromeLabs/pwa-wp/blob/56b3d8d7662a043a8115c85577ecda1f0ad59485/integrations/class-wp-service-worker-admin-assets-integration.php#L156, where the code assumes the `wp-admin` folder is in the root of the domain.

A possible solution would be to rely on the `site_url()` function to get the right location: If WordPress is in a subdirectory, the site URL would include that. So if it does, that directory should be added to the actual folder as a prefix.

(FWIW since that method is also used for image files in `wp-includes`, the bug is probably present there as well. The same approach I suggested above should fix that problem too.)

**Comment by westonruter** [comment]
The integrations are deprecated per #403 so probably best to just turn that off.

**Comment by felixarntz** [comment]
Oh... Fair point 😄
