### ISSUE TITLE
Uygulama hakkında 

### ISSUE THREAD

**Issue by EchoBilisim** [xwp/pwa-wp#849]
Merhaba uygulamayı kullanıyorum çok güzel ancak şöyle bir öneride bulunmak istiyorum uygulama olarak yükleniyor ama uygulama gibi durmuyor uygulamanın üstünde site adı filan yazıyor onu kaldırmanız gerekli bence o zaman tam uygulama gibi durur ekran görüntüsü ekledim işaretledim o bölüm olmaması lazım.

![IMG_20220928_172757](https://user-images.githubusercontent.com/17055352/192805991-ee4a5d53-44ed-41ac-9a1a-86d1921f9d4a.jpg)

**Comment by westonruter** [comment]
Hello. Please try this: https://github.com/GoogleChromeLabs/pwa-wp/wiki/FAQ#how-can-i-have-my-pwa-install-like-a-standalone-app

**Comment by EchoBilisim** [comment]
> Merhaba. Lütfen şunu deneyin: https://github.com/GoogleChromeLabs/pwa-wp/wiki/FAQ#how-can-i-have-my-pwa-install-like-a-standalone-app

Merhaba kodlama bilgim fazla yok bu kodu nereye uygulamam gerekiyor?

**Comment by westonruter** [comment]
You can put it in your theme's `functions.php` file or better put it in a custom plugin (just a single PHP file). There are tutorials for how to do this, for example: https://www.wpbeginner.com/wp-tutorials/how-to-create-a-wordpress-plugin/

**Comment by EchoBilisim** [comment]
Çok teşekkür ederim şimdi çözdüm.

sayenizde istediğim gibi oldu tekrardan çok teşekkür ederim

**Comment by westonruter** [comment]
I am glad I was able to help!
