### ISSUE TITLE
Implement Offline Commenting

### ISSUE THREAD

**Issue by alcurrie** [xwp/pwa-wp#87]
**As as WordPress developer, I would like to be able to allow site visitors and admin users add comments to posts even when offline**

- [x] _AC 1:_ **Build comment offline sync functionality into PWA plugin.** When viewing a page or post with commenting enabled, a user will be able to make a comment and have that comment saved and posted once the user is back online
- [x] _AC 2:_ **The user interface for offline commenting will be easy to use and include appropriate messaging.** By default the plugin should show an offline page where submitting a comment when offline, with a message like “you are offline, but we will post your comment will be posted when your device comes back online.” This should integrate with the offline template to show custom messages similar to how the `500` page can show custom messages.   (See related issue in the twentyseventeen-weston repo, [Issue 4 Optimize the design of the Offline/500 page to be more engaging for the user](https://github.com/westonruter/twentyseventeen-westonson/issues/4))

- [x] _AC 3:_ A theme must be able to override the offline template and messaging for commenting failures.
- [ ] _AC 4:_ Site on Using our AMP and PWA plugins, enable this offline commenting support via a theme declaration.
- [ ] _AC 5:_ Intercept the amp-form action-xhr request (to submit the form) and when failed return a custom success message to be shown below the form

**Offline Routing and messaging**
- [ ] _AC 6:_  If AMP is enabled, The amp-live-list should continue to update in real time, showing the new comment when background sync happens or if the comment was submitted successfully right away. The error message should probably appear in the context of the posted comment.
- [x] _AC 7:_ If AMP is not enabled, route the user to the site's offline page and allow a theme developer to serve the offline message from AC2/AC3. Make sure the the ability for service worker to populate content of the offline template is added.

For reference, here was the original <amp-live-list> PR from the AMP plugin:
https://github.com/Automattic/amp-wp/issues/1028

**Comment by westonruter** [comment]
See changes to Workbox background sync in v4: https://github.com/GoogleChrome/workbox/pull/1710

**Comment by postphotos** [comment]
Hi @westonruter @alcurrie - I've updated the ACs above based on our meeting today.

**Comment by alcurrie** [comment]
@miina  / @jwold  - I added a link to the new - design of the [Offline template story](https://github.com/westonruter/twentyseventeen-westonson/issues/4) to this ticket as I think it makes sense to make sure that the design/functionality for the offline template work together with the user interface for the offline templating in AC-2 above.  

@miina  what's the status of that part of the functionality.  Do you already have clarity on how that interface will work and link to the Offline template, or would it make sense to AC-2 be broken out to follow-up up on how that interface and user message would appear?

**Comment by miina** [comment]
@alcurrie Thanks for adding the link. To add some background information for AC2: the AC2 in this ticket is for the PWA Plugin and will be part of what will be proposed to merge to WordPress Core. It will leverage the already existing Offline templating system and _already existing_ default design and won't be influenced by the linked ticket for [design of the Offline template story](https://github.com/westonruter/twentyseventeen-westonson/issues/4), however, the linked ticket will be based on what we're building within this ticket and is dependent on AC2.

On status of the functionality part: yes, it's clear how to implement the ticket, no need to break AC-2 to follow-up, thank you for asking. Most of it is already built previously. What we're adding now is the comments-specific messaging for the users and possibility to override it -- overriding will be done by developers only and won't have any user interface.

This is how the offline page template for comments is looking like by default -- within the child theme we're going to override this template to show a custom version of it:
![screen shot 2018-10-19 at 1 26 29 pm](https://user-images.githubusercontent.com/3294597/47231342-feee6880-d3a2-11e8-9462-fe5b8f1240f4.png)

**Comment by alcurrie** [comment]
@miina Thanks so much for clarifying and for providing the background and context. It's great to have the details, and the screen shot example. So based on that it sounds like this issue will affect the 'AC2' and the  [Offline template story](https://github.com/westonruter/twentyseventeen-westonson/issues/4) not the other way around. I'll update that issue with these details.   cc. @jwold

**Comment by alcurrie** [comment]
@miina  - I just wanted to flag that @westonruter 's  note from   https://github.com/xwp/pwa-wp/issues/90#issuecomment-431061462 re using the offline page could also to list out the URLs that have been cached for offline access.

**Comment by miina** [comment]
@alcurrie Thanks for bringing that out. Probably we could add listing out URLs as an optional addition if we have time, not as a requirement.

Also, this seems to be more generally related to the offline page, not necessarily offline commenting. Or did you mean this specifically related to offline commenting, @westonruter?

**Comment by westonruter** [comment]
Right, my https://github.com/xwp/pwa-wp/issues/90#issuecomment-431061462 is an optional addition, not a requirement. It's not related to offline commenting.
