### ISSUE TITLE
Failed to register a ServiceWorker 

### ISSUE THREAD

**Issue by DanielCryptoK** [xwp/pwa-wp#873]
Hi,

I have just installed your plugin and get the below error. How do I fix it?

Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://bitcoin-casino-no-deposit-bonus.com/') with script ('https://bitcoin-casino-no-deposit-bonus.com/wp.serviceworker'): The script has an unsupported MIME type ('text/html').

Also I can not find how to change any settings for your plugin?? Is it one you just activate and do not have to change any settings?

**Comment by westonruter** [comment]
> Uncaught (in promise) DOMException: Failed to register a ServiceWorker for scope ('https://bitcoin-casino-no-deposit-bonus.com/') with script ('https://bitcoin-casino-no-deposit-bonus.com/wp.serviceworker'): The script has an unsupported MIME type ('text/html').

I just checked the response type and it is `text/javascript` not `text/html`. My guess is you have a caching plugin that is caching the service worker script response and is erroneously sending back cached responses as `text/html` as opposed to `text/javascript`. You can exclude `/wp.serviceworker` from caching as a workaround for this. Ideally the caching plugin would be caching the `Content-Type` response header as well and sending this as part of a cached response.

> Also I can not find how to change any settings for your plugin?? Is it one you just activate and do not have to change any settings?

The settings are integrated into the other admin screens. For example on the General settings screen there is a Short Name field that appears if the title is sufficiently long. Also, more importantly, there is an Offline Browsing checkbox on the Reading settings screen.
