### ISSUE TITLE
Is it possible to cache AJAX requests?

### ISSUE THREAD

**Issue by nickchomey** [xwp/pwa-wp#874]
I have a highly dynamic site that loads a lot of the content via AJAX requests. I've tried a few different PWA plugins and none have any capability to cache any of this - perhaps especially since they all use the same `wp-admin/admin-ajax.php` endpoint. So, if I cache a page for offline usage, the html that is generated on the initial page load is displayed, but anything that is retrieved/displayed via AJAX remains blank/missing.

Is there any way that this could be implemented within this plugin? I assume some sort of event listener for jQuery AjaxSend events would be needed, and then look in the request body for which hook/function is being targeted as well as what specific data is being passed (current user id, current page, etc...). 

I think this would be very important for bringing PWA capabilities to more modern/complex sites.

Thanks!

**Comment by westonruter** [comment]
This would be simplified greatly if you could use the WordPress REST API. Nevertheless, it should still be possible. Are the requests `GET` requests or `POST` requests?

**Comment by nickchomey** [comment]
Yeah, rest Api would be nice, but it doesn't seem at all practical for me to recode all of the JavaScript in the theme and plugins that I'm using to point to rest api endpoints...

I assume it's almost always POST, given that's how most people tend to use admin-ajax.php - even if it's really just a GET (data retrieval) request. Some would be true POST (add an entry to the dB) requests though.

Can you think of any approach to make this happen, be it some sort of rewrite or custom endpoints, or some custom service worker event listener that can parse the admin Ajax request and add the responses to the CacheStorage as appropriate? I'm obviously happy to do all of the custom work - I just don't know what the right approach might be!

Thanks!

**Comment by westonruter** [comment]
If you can update your JS to use `GET` requests that would likely make it much easier to add service worker caching. If not, then there is this starting point: https://stackoverflow.com/a/59737346/93579

See also https://github.com/GoogleChrome/workbox/issues/2574

But still, switching to `GET` will make this much more feasible.

**Comment by nickchomey** [comment]
Thanks very much.

I suspect that it would be impossibly difficult to change POST to GET because I'd need to override the JS from the dozens of plugins that I'm using, which would get overridden on each update. Moreover, if I'm not mistaken, it seems like using POST for all AJAX requests is actually recommended in many cases (or, at least, the de facto standard).

So, it really does seem like integrating something like what is described those links into this plugin would be the appropriate way to handle this, so that all WP users could easily make use of it rather than me doing some custom work in isolation. 

Here's a couple other related links as well, for reference. 
* https://github.com/GoogleChrome/workbox/issues/1547
* https://github.com/GoogleChrome/workbox/issues/2092) 

Do you think this is something that your team might consider implementing at some point?

**Comment by westonruter** [comment]
I think the situation is summarized well by Jeff here: https://github.com/GoogleChrome/workbox/issues/1547#issuecomment-399507780:

> The underling Cache Storage API [doesn't support](https://w3c.github.io/ServiceWorker/#cache-put) using `POST` requests as the key when storing a response. This is not a limitation specific to Workbox.
> 
> In general, since `POST` requests are meant to mutate server-side state, caching them locally and replaying the response tends not to be a great idea.
> 
> You can either write something by hand to process the incoming `POST` request and convert it into a `GET` prior to storing it, or, better yet, work with the API you're using to ensure that they also support `GET` requests.

So it seems like it's _possible_ to use Workbox to cache POST requests, but you have to do extra work to convert the request to a GET for caching purposes. You'd also have to make sure that you only ever cache POST requests which are _actually_ idempotent. You wouldn't want to accidentally cache a POST request for something like adding a comment reaction or providing a star rating to a product. This would require that you manually opt-in to each POST request that you actually want to be cached.

This being the case, I don't think it's in the scope of this plugin to implement caching for POST requests, as it would be impossible to implement in a turnkey way.

**Comment by nickchomey** [comment]
Understood, thanks for the clarification. I've found various articles/resources in addition to what you shared that give some guidance on how to implement something like this, seemingly without converting anything. But, yes, I'll have to be careful to only cache GET and pseudo-GET (POST that's actually GET) requests. I'll give it a shot soon!

**Comment by nickchomey** [comment]
p.s. this existing issue (https://github.com/GoogleChromeLabs/pwa-wp/issues/213) seems very relevant to the topic discussed here...
