### ISSUE TITLE
Adapt Surma's CDS'17 Progressive WP Theme leveraging Workbox and PWA Plugin

### ISSUE THREAD

**Issue by alcurrie** [xwp/pwa-wp#88]
**As a WordPress developer, I should have the theme developed by Surma for his CDS 2017 talk work well with the PWA Feature Plugin for WordPress so I can activate the new features from the PWA feature plugin on my website.**

_AC 1:_ The updated Theme will use proper the WordPress templating approach and extract functionality from theme provided by the PWA Feature Plugin: https://wordpress.org/plugins/pwa/
_AC 2:_ The theme will work properly after adapting it to work with the PWA feature plugin
_AC 3:_ Hook the existing progressive features into the theme codebase

**_Background:_** 
_His talk:_
https://www.youtube.com/watch?v=Di7RvMlk9io
_Repo for the theme:_
https://github.com/GoogleChromeLabs/ProgressiveWordPress
_Demo site (as of today):_
https://pwp.dassur.ma/
_Example of Google offline search_
https://www.theverge.com/2017/1/18/14308830/android-google-offline-searches-mobile

**Comment by westonruter** [comment]
If we use my child theme of Twenty Seventeen instead, then we should:

* Work on improving the loading indicator for streaming.
* Animate the header transition from homepage to blog page.
* AMP commenting live list
