### ISSUE TITLE
Option to disable the `theme-color` meta tag

### ISSUE THREAD

**Issue by rafaucau** [xwp/pwa-wp#901]
I have `theme-color` already added in the theme. In addition, in my theme these colors change depending on the current category.
```html
<meta name="theme-color" content="#00C317" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#00800F" media="(prefers-color-scheme: dark)">
```
This plugin overwrites those colors. 

It would be nice if this was in a separate method so that it would be possible to remove it with an action/filter.
https://github.com/GoogleChromeLabs/pwa-wp/blob/644c267c3461a5bfc1c7d4f6b997c2b566dda798/wp-includes/class-wp-web-app-manifest.php#L81-L85

**Comment by rafaucau** [comment]
BTW in this plugin there is no check if `theme_color` is set in the manifest.

```php
add_filter( 'web_app_manifest', static function ( array $manifest ) {
  unset( $manifest['theme_color'] );

  return $manifest;
} );
```
![image](https://user-images.githubusercontent.com/25438601/210400854-0d3dcfb1-73b8-4e32-bf4f-9a7ef64bbdeb.png)

**Comment by westonruter** [comment]
So at the very least this line:

https://github.com/GoogleChromeLabs/pwa-wp/blob/68ff77e55a21b04d24b6e0e9b0664a6ac9db4972/wp-includes/class-wp-web-app-manifest.php#L85

Should be changed to:

```php
<?php if ( ! empty( $manifest['theme_color'] ) ) : ?>
    <meta name="theme-color" content="<?php echo esc_attr( $manifest['theme_color'] ); ?>"> 
<?php endof; ?>
```

That would then resolve the issue for you if you are filtering `web_app_manifest`?

**Comment by rafaucau** [comment]
Yes, but if I want to leave it in `/wp-json/wp/v2/web-app-manifest` and just remove it from the HTML, then such a code can be used:
```php
<?php if ( ! empty( $manifest['theme_color'] ) && apply_filters( 'web_app_add_html_head_theme_color', true ) ) : ?>
  <meta name="theme-color" content="<?php echo esc_attr( $manifest['theme_color'] ); ?>">
<?php endif; ?>
```

```php
add_filter( 'web_app_add_html_head_theme_color', '__return_false' );
```

**Comment by rafaucau** [comment]
However, the filter is not needed, because I actually can do such a thing:
```php
add_filter( 'web_app_manifest', static function ( array $manifest ) {
  if ( ! defined( 'REST_REQUEST' ) ) {
    unset( $manifest['theme_color'] );
  }

  return $manifest;
} );
```
