### ISSUE TITLE
Wait until page load to register service worker

### ISSUE THREAD

**Issue by nisbet-hubbard** [xwp/pwa-wp#946]
I wonder what would be the right approach to delaying registering the service worker until the page loads, so the precaching isn’t render-blocking. Can we achieve something along the lines of this within the framework of the plugin?

```
window.addEventListener("load", () => {
			    if ("serviceWorker" in navigator) {
			      navigator.serviceWorker.register("/sw.js");
			    }
			  });
```

**Comment by westonruter** [comment]
This should already be the case. The service worker is registered here:

https://github.com/GoogleChromeLabs/pwa-wp/blob/4da439f09b833f4792f68bcbc057b4bf3b303fae/wp-includes/service-workers.php#L184-L195

(Note that a `module` type is asynchronous.)

And the `register` method there in the `Workbox` class [waits until the window `load` event has fired](https://github.com/GoogleChrome/workbox/blob/95f97a207fd51efb3f8a653f6e3e58224183a778/packages/workbox-window/src/Workbox.ts#L100-L115).

**Comment by nisbet-hubbard** [comment]
Thank you very much for taking the time to explain this!
