### ISSUE TITLE
Duplicate short name setting

### ISSUE THREAD

**Issue by swissspidy** [xwp/pwa-wp#952]
I see the short name setting at the top:

<img width="611" alt="Screenshot 2023-03-24 at 17 48 47" src="https://user-images.githubusercontent.com/841956/227589368-373ecfc0-935d-4cc5-9469-76c1efe429f3.png">

But then there's also an empty section at the bottom:

<img width="486" alt="Screenshot 2023-03-24 at 17 49 04" src="https://user-images.githubusercontent.com/841956/227589418-98921a47-7bc6-4e37-9630-e6b2043feee4.png">

I suspect it's because the settings field is moved via JS and there's a conflict with another plugin or a change in core that breaks this functionality.

**Comment by westonruter** [comment]
Good catch. I can reproduce this issue on a site with only this plugin active. Investigating.

**Comment by westonruter** [comment]
Got it: #954
