### ISSUE TITLE
Erroneous use of preloadResponse

### ISSUE THREAD

**Issue by westonruter** [xwp/pwa-wp#96]
In Chrome Canary I'm seeing an error in the console:

> The service worker navigation preload request was cancelled before 'preloadResponse' settled. If you intend to use 'preloadResponse', use waitUntil() or respondWith() to wait for the promise to settle.

Something isn't right with this code, apparently:

https://github.com/xwp/pwa-wp/blob/c3b06fe6f7cfc78538c2b256448a41e4a050602d/wp-includes/js/service-worker-navigation-routing.js#L62-L77

**Comment by jeffposnick** [comment]
Are you seeing that message logged for all navigations, or just a subset of navigations (navigations while offline, navigations to a non-existent URL, etc.)?

Is navigation broken when this error occurs? Or does navigation proceed (presumably without using the preloaded response)?

**Comment by westonruter** [comment]
I'm not seeing navigation being broken when this error is displayed in the console. I see it every time I initiate navigation between URLs in the wp-admin as I would normally (existing URLs while being online).

**Comment by westonruter** [comment]
I'm still trying to understand why a blacklisted URL for the `NavigationRoute` causes the `preloadResponse` to be cancelled, as opposed to just using it as the response.

Given navigation preload being enabled with the `NavigationRoute`  registered, for whitelisted URLs we handle the request by awaiting the `preloadResponse`. For blacklisted URLs, shouldn't Workbox by default use the preloadResponse in the same way?

**Comment by thearegee** [comment]
@westonruter did you ever find a solution for this, I'm getting the same issue with our implementation

**Comment by westonruter** [comment]
It should be fixed in the latest version of the plugin, in particular after #178.
