### ISSUE TITLE
WP_Service_Worker_Site_Icon_Integration-deprecation Warning

### ISSUE THREAD

**Issue by luukee** [xwp/pwa-wp#972]
Hello, not sure how we remove these errors from our site? 

```
console.warn("The WP_Service_Worker_Site_Icon_Integration integration in the PWA plugin is no longer being considered WordPress core merge. See https:\/\/github.com\/GoogleChromeLabs\/pwa-wp\/issues\/403");
console.warn("The WP_Service_Worker_Fonts_Integration integration in the PWA plugin is no longer being considered WordPress core merge. See https:\/\/github.com\/GoogleChromeLabs\/pwa-wp\/issues\/403");
console.warn("The WP_Service_Worker_Admin_Assets_Integration integration in the PWA plugin is no longer being considered WordPress core merge. See https:\/\/github.com\/GoogleChromeLabs\/pwa-wp\/issues\/403");
console.warn("The WP_Service_Worker_Scripts_Integration integration in the PWA plugin is no longer being considered WordPress core merge. See https:\/\/github.com\/GoogleChromeLabs\/pwa-wp\/issues\/403");
console.warn("The WP_Service_Worker_Styles_Integration integration in the PWA plugin is no longer being considered WordPress core merge. See https:\/\/github.com\/GoogleChromeLabs\/pwa-wp\/issues\/403");

```

They seem to be persistent across every page of our site & I cannot find any info on how to fix. Thanks!

![Screenshot 2023-04-21 at 12 15 46 PM](https://user-images.githubusercontent.com/30611098/233717252-5cf4653e-2d4f-4410-a970-1f7860203165.png)

**Comment by westonruter** [comment]
These aren't errors but just warnings. I recommend turning off those integrations since they are deprecated. Instead rely on the Offline Browsing which you can enable in Reading Settings.

**Comment by luukee** [comment]
Thanks for getting back @westonruter. How do I disable the mentioned integrations?

Thanks again,
Luke

**Comment by westonruter** [comment]
The integrations are opt-in via by doing `add_theme_support( 'service_worker', ... )`. I'm guessing your theme is doing this. Maybe your theme has a switch to turn that off. Otherwise you could do `remove_theme_support( 'service_worker' )`, perhaps at the `after_setup_theme` action.

**Comment by luukee** [comment]
Good to go. Thanks @westonruter
